
##############################
# Country definition for SOV #
##############################

province =
{ id         = 133
  anti_air   = 4
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # Murmansk
province =
{ id         = 154
  anti_air   = 4
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Archangelsk
province =
{ id          = 163
  air_base    = { size = 4 current_size = 4 }
  landfort    = 5
  anti_air    = 3
}               # Stalingrad
province =
{ id          = 175
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  anti_air    = 4
}               # Moscow
province =
{ id       = 181
  air_base = { size = 3 current_size = 3 }
  anti_air = 1
}            # Kaluga
province =
{ id          = 187
  synthetic_rares = 1
  ic	      = 3
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  coastalfort = 5
}               # Leningrad
province = { id = 191 anti_air = 1 } # Porkhov
province =
{ id       = 201
  air_base = { size = 6 current_size = 6 }
}            # Opochka
province =
{ id       = 217
  air_base = { size = 2 current_size = 2 }
  anti_air = 2
}            # Vitebsk
province = { id = 219 anti_air = 3 } # Smolensk
province =
{ id       = 220
  air_base = { size = 8 current_size = 8 }
}            # Mogilev
province =
{ id       = 233
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # Odessa
province = { id = 234 ic = 1 } # Kherson
province = { id = 236 ic = 1 } # Krivoy Rog
province =
{ id       = 238
  ic	      = 2
  air_base = { size = 8 current_size = 8 }
  anti_air = 3
}            # Kiev
province = { id = 246 anti_air = 2 } # Zaporozhye
province =
{ id       = 248
  air_base = { size = 2 current_size = 2 }
  anti_air = 1
}            # Kharkov
province =
{ id          = 253
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 6 current_size = 6 }
  landfort    = 3
  coastalfort = 5
}               # Sevastopol
province =
{ id       = 258
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # Rostov
province = { id = 263 anti_air = 1 } # Svoboda
province =
{ id       = 264
  air_base = { size = 2 current_size = 2 }
}            # Pavlovsk
province =
{ id       = 273
  air_base = { size = 2 current_size = 2 }
}            # Gomel
province = { id = 277 anti_air = 2 } # Bryansk
province =
{ id       = 282
  air_base = { size = 5 current_size = 5 }
}            # Orel
province =
{ id       = 289
  air_base = { size = 2 current_size = 2 }
}            # Demyansk
province =
{ id       = 1163
  air_base = { size = 1 current_size = 1 }
}            # Yakutsk
province =
{ id         = 1175
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
}              # Ocha
province =
{ id       = 1368
  air_base = { size = 1 current_size = 1 }
}            # Komsomolsk-na-Amure
province =
{ id          = 1372
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 1
  coastalfort = 3
}               # Vladivostok
province =
{ id       = 1416
  air_base = { size = 3 current_size = 3 }
}            # Irkutsk
province = { id = 1422 ic = 6 } # Alma-Ata
province = { id = 1427 ic = 3 } # Tashkent
province = { id = 1429 ic = 5 } # Frunze
province = { id = 1485 ic = 4 } # Stalinabad
province = { id = 1490 ic = 3 } # Ashgabat
province =
{ id       = 1523
  air_base = { size = 2 current_size = 2 }
}            # Tynda
province =
{ id         = 1525
  anti_air   = 2
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # Okhotsk
province =
{ id       = 1538
  air_base = { size = 1 current_size = 1 }
}            # Severo-Yenisejsk
province =
{ id       = 1544
  air_base = { size = 2 current_size = 2 }
}            # Tomsk
province = { id = 1548 ic = 6 } # Novosibirsk
province =
{ id       = 1550
  air_base = { size = 2 current_size = 2 }
}            # Semipalatinsk
province =
{ id       = 1552
  air_base = { size = 1 current_size = 1 }
}            # Omsk
province = { id = 1572 ic = 4 } # Sverdlovsk
province =
{ id       = 1574
  air_base = { size = 1 current_size = 1 }
}            # Chelyabinsk
province =
{ id       = 1827
  air_base = { size = 2 current_size = 2 }
}            # Naberezhnye Chelny
province =
{ id       = 1828
  air_base = { size = 4 current_size = 4 }
  synthetic_rares = 1
}            # Kuybyshev
province =
{ id       = 1832
  air_base = { size = 3 current_size = 3 }
}            # Saratov
province =
{ id       = 1838
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Astrakhan
province =
{ id       = 1839
  air_base = { size = 2 current_size = 2 }
}            # Novouzensk
province =
{ id         = 1848
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Batum
province = { id = 1850 ic = 7 } # Tblisi
province = { id = 1856 ic = 5 } # Yerevan

#####################
# Country main data #
#####################

country =
{ tag                    = SOV
  regular_id             = RUS
  intrinsic_gov_type     = leninist
  capital                = 175
  #ground_def_eff         = 0.200
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 30
  consumer = 0.0000 
  supply = 0.1700 
  production = 0.8300 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  expense_synthetic = 0.0000 
  expense_synthetic_rares = 0.0000  
  manpower               = 2974.4 # 3000 - building queue
  dissent                = 15
  transports             = 135
  escorts                = 30
  diplomacy =
  { relation =
    { tag        = AFG
      value      = 1
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = BRA value = -50 }
    relation =
    { tag        = BUL
      value      = 15
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = CHC value = 100 }
    relation = { tag = CZE value = 100 }
    relation = { tag = ENG value = -25 }
    relation =
    { tag        = EST
      value      = -30
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = FIN value = 1 }
    relation =
    { tag        = FRA
      value      = 100
      guaranteed = { day = 7 month = january year = 1935 }
    }
    relation = { tag = GER value = 1 }
    relation = { tag = GRE value = 15 }
    relation = { tag = IRE value = 1 }
    relation = { tag = JAP value = -10 }
    relation =
    { tag        = LAT
      value      = -30
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation =
    { tag        = LIT
      value      = -30
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = MON value = 150 access = yes }
    relation =
    { tag        = PER
      value      = -20
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = POL value = -50 }
    relation = { tag = ROM value = 1 }
    relation = { tag = SAU value = 1 }
    relation = { tag = SIK value = 125 }
    relation = { tag = SPR value = -10 }
    relation =
    { tag        = TAN
      value      = 200
      guaranteed = { day = 16 month = may year = 1935 }
      access     = yes
    }
    relation =
    { tag        = TUR
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = URU value = -100 }
    relation = { tag = USA value = 35 }
    relation =
    { tag        = SCH
      value      = 1
      guaranteed = { day = 16 month = may year = 1935 }
    }
  }
  SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  SpyInfo                = { country = "ENG" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "CZE" NumberOfSpies = 1 }
  SpyInfo                = { country = "AUS" NumberOfSpies = 1 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 2 }
  SpyInfo                = { country = "POL" NumberOfSpies = 3 }
  SpyInfo                = { country = "SWE" NumberOfSpies = 2 }
  SpyInfo                = { country = "NOR" NumberOfSpies = 1 }
  SpyInfo                = { country = "FIN" NumberOfSpies = 3 }
  SpyInfo                = { country = "YUG" NumberOfSpies = 3 }
  SpyInfo                = { country = "HUN" NumberOfSpies = 2 }
  SpyInfo                = { country = "BUL" NumberOfSpies = 3 }
  SpyInfo                = { country = "BEL" NumberOfSpies = 1 }
  SpyInfo                = { country = "DEN" NumberOfSpies = 1 }
  SpyInfo                = { country = "CXB" NumberOfSpies = 2 }
  SpyInfo                = { country = "MON" NumberOfSpies = 3 }
  SpyInfo                = { country = "CGX" NumberOfSpies = 1 }
  SpyInfo                = { country = "USA" NumberOfSpies = 3 }
  SpyInfo                = { country = "GUA" NumberOfSpies = 1 }
  SpyInfo                = { country = "GRE" NumberOfSpies = 1 }
  SpyInfo                = { country = "CYN" NumberOfSpies = 3 }
  SpyInfo                = { country = "CSX" NumberOfSpies = 1 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 3 }
  SpyInfo                = { country = "ROM" NumberOfSpies = 2 }
  SpyInfo                = { country = "LIT" NumberOfSpies = 2 }
  SpyInfo                = { country = "LUX" NumberOfSpies = 1 }
  SpyInfo                = { country = "POR" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 3 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 2 }
  SpyInfo                = { country = "SCH" NumberOfSpies = 1 }
  nationalprovinces      = { 1372 1373 1371 1370 1369 1367 1366 1527 1529 1528 1526 1523 1410 1525 1524 1409 1164 1165 1166 1167 1170 1171 1172 1405
                             1174 1175 1522 1521 1384 1383 1520 1416 1415 1414 1413 1162 1412 1411 1163 1159 1160 1158 1417 1558 1557 1423 1556 1550
                             1549 1547 1546 1559 1561 1560 1562 1563 1532 1537 1538 1545 1544 1548 1543 1540 1539 1536 1535 1533 1534 1157 1531 1156
                             1155 1154 1565 1564 1571 1597 1598 1554 1555 1553 1552 1594 1596 1573 1593 1592 1591 1590 1589 1588 1587 1424 1586 1585
                             1584 1583 1581 1576 1575 1574 1572 1566 1567 1570 1577 1578 1580 1582 1579 1569 1568 1150 1151 1152 1153 1773 1772 1771
                             154  1840 1841 165  153  151  152  150  135  134  133  1838 1847 1857 1849 1850 1848 1845 1844 1846 1843 255  256  257 
                             270  1842 1837 271  164  1833 1834 1836 1839 1827 1828 1835 1829 1832 1831 1830 252  253  254  1777 1778 1776 1775 1780
                             1781 1782 1783 1774 163  162  161  160  159  157  156  158  155  169  168  167  179  180  166  178  177  170  171  172 
                             173  174  175  176  181  182  183  184  190  191  189  185  186  187  188  192  200  201  212  225  226  227  228  231 
                             232  233  234  251  250  235  236  237  238  239  240  220  272  241  273  274  275  276  277  278  279  280  281  282 
                             283  284  249  258  259  260  248  247  243  262  261  269  268  267  266  265  264  263  1490 1491 1485 1487 1488 1427
                             1428 1426 1425 1429 94   215  216  217  218  219  221  242  244  245  246  285  286  287  288  289  1149 1161 1368 1422
                             1489 1856 1858 1907 1541 1542 1551 1874 1176
                           }
  ownedprovinces         = { 1372 1373 1371 1370 1369 1367 1366 1527 1529 1528 1526 1523 1410 1525 1524 1409 1164 1165 1166 1167 1170 1171 1172 1405
                             1175 1522 1521 1384 1383 1520 1416 1415 1414 1413 1162 1412 1411 1163 1159 1160 1158 1417 1558 1557 1423 1556 1550 1549
                             1547 1546 1559 1561 1560 1562 1563 1532 1537 1538 1545 1544 1548 1543 1540 1539 1536 1535 1533 1534 1157 1531 1156 1155
                             1154 1565 1564 1571 1597 1598 1554 1555 1553 1552 1594 1596 1573 1593 1592 1591 1590 1589 1588 1587 1424 1586 1585 1584
                             1583 1581 1576 1575 1574 1572 1566 1567 1570 1577 1578 1580 1582 1579 1569 1568 1150 1151 1152 1153 1773 1772 1771 154 
                             1840 1841 165  153  151  152  150  135  134  133  1838 1847 1857 1849 1850 1848 1845 1844 1846 1843 255  256  257  270 
                             1842 1837 271  164  1833 1834 1836 1839 1827 1828 1835 1829 1832 1831 1830 252  253  254  1777 1778 1776 1775 1780 1781
                             1782 1783 1774 163  162  161  160  159  157  156  158  155  169  168  167  179  180  166  178  177  170  171  172  173 
                             174  175  176  181  182  183  184  190  191  189  185  186  187  188  192  200  201  212  225  226  227  228  231  232 
                             233  234  251  250  235  236  237  238  239  240  220  272  241  273  274  275  276  277  278  279  280  281  282  283 
                             284  249  258  259  260  248  247  243  262  261  269  268  267  266  265  264  263  1490 1491 1485 1487 1488 1427 1428
                             1426 1425 1429 94   215  216  217  218  219  221  242  244  245  246  285  286  287  288  289  1149 1161 1368 1422 1489
                             1856 1858 1907 1541 1542 1551 1874
                           }
  controlledprovinces    = { 1372 1373 1371 1370 1369 1367 1366 1527 1529 1528 1526 1523 1410 1525 1524 1409 1164 1165 1166 1167 1170 1171 1172 1405
                             1175 1522 1521 1384 1383 1520 1416 1415 1414 1413 1162 1412 1411 1163 1159 1160 1158 1417 1558 1557 1423 1556 1550 1549
                             1547 1546 1559 1561 1560 1562 1563 1532 1537 1538 1545 1544 1548 1543 1540 1539 1536 1535 1533 1534 1157 1531 1156 1155
                             1154 1565 1564 1571 1597 1598 1554 1555 1553 1552 1594 1596 1573 1593 1592 1591 1590 1589 1588 1587 1424 1586 1585 1584
                             1583 1581 1576 1575 1574 1572 1566 1567 1570 1577 1578 1580 1582 1579 1569 1568 1150 1151 1152 1153 1773 1772 1771 154 
                             1840 1841 165  153  151  152  150  135  134  133  1838 1847 1857 1849 1850 1848 1845 1844 1846 1843 255  256  257  270 
                             1842 1837 271  164  1833 1834 1836 1839 1827 1828 1835 1829 1832 1831 1830 252  253  254  1777 1778 1776 1775 1780 1781
                             1782 1783 1774 163  162  161  160  159  157  156  158  155  169  168  167  179  180  166  178  177  170  171  172  173 
                             174  175  176  181  182  183  184  190  191  189  185  186  187  188  192  200  201  212  225  226  227  228  231  232 
                             233  234  251  250  235  236  237  238  239  240  220  272  241  273  274  275  276  277  278  279  280  281  282  283 
                             284  249  258  259  260  248  247  243  262  261  269  268  267  266  265  264  263  1490 1491 1485 1487 1488 1427 1428
                             1426 1425 1429 94   215  216  217  218  219  221  242  244  245  246  285  286  287  288  289  1149 1161 1368 1422 1489
                             1856 1858 1907 1541 1542 1551 1874
                           }
  # Rocket Test and Research Facility
  # Air Doctrines 1936
  # ################
  techapps               = { 5550  9010  9020  9030  9040  4010  4020  4120  4130  2010  2020  2030  2150  2290  2300  2310  2320  2450  5010  5080 
                             5090  5190  1010  1110  1190  1230  1020  1200  1210  1220  1310  6210  6300  2400  2040  8010  8020  8030  8040  8050 
                             8070  3010  3020  3030  3070  3080  3130  3140  3190  3250  3260  3270  3400  3410  3420  14000 5290
                           }
  blueprints             = { 1070 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 10
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 6
    interventionism   = 4
  }
  headofstate            = { type = 9 id = 4001 }
  headofgovernment       = { type = 9 id = 4002 }
  foreignminister        = { type = 9 id = 4003 }
  armamentminister       = { type = 9 id = 4004 }
  ministerofsecurity     = { type = 9 id = 4005 }
  ministerofintelligence = { type = 9 id = 4006 }
  chiefofstaff           = { type = 9 id = 4007 }
  chiefofarmy            = { type = 9 id = 4008 }
  chiefofnavy            = { type = 9 id = 4009 }
  chiefofair             = { type = 9 id = 4010 }

  nationalidentity = "policy_identity_defensive"
	socialpolicy = "policy_social_conformism"
	nationalculture = "policy_culture_civic"

 ########################################
	### Soviet Land OOB ###
 ########################################
  landunit =
  { id       = { type = 10848 id = 1 }
    name     = "1st Mechanized Corps"
    location = 187
    division =
    { id       = { type = 10848 id = 2 }
      name     = "163. Motostrelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
    division =
    { id       = { type = 10848 id = 3 }
      name     = "177. Strelkovaya Diviziya"
      strength = 60
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 4 }
      name     = "191. Strelkovaya Diviziya"
      strength = 60
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 5 }
      name     = "8. 'Minskaya' Strelk. Div."
      strength = 60
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 6 }
    name     = "7ya Armiya"
    location = 152
    division =
    { id       = { type = 10848 id = 7 }
      name     = "54. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 8 }
      name     = "71. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 9 }
    name     = "14ya Armiya"
    location = 191
    division =
    { id       = { type = 10848 id = 10 }
      name     = "122. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 11 }
      name     = "104. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 12 }
      name     = "14. 'Krivorozhskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 13 }
      name     = "1. Tankovaya Diviziya"
      strength = 30
      type     = light_armor
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10848 id = 14 }
    name     = "23ya Armiya"
    location = 216
    division =
    { id       = { type = 10848 id = 15 }
      name     = "142. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 16 }
      name     = "43. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 17 }
      name     = "198. Moto. Strelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10848 id = 18 }
    name     = "8ya Armiya"
    location = 219
    division =
    { id       = { type = 10848 id = 19 }
      name     = "10. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 20 }
      name     = "48. Strelkovaya Diviziya"
      strength = 80
      extra    = artillery
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 21 }
      name     = "202. Moto. Strelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = engineer
    }
  }
  landunit =
  { id       = { type = 10848 id = 22 }
    name     = "11ya Armiya"
    location = 220
    division =
    { id       = { type = 10848 id = 23 }
      name     = "5. 'Vitebskaya' Strelk. Div."
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 24 }
      name     = "179. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 25 }
      name     = "184. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 26 }
      name     = "33. 'Belorusskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 27 }
      name     = "2. Tankovaya Diviziya"
      strength = 80
      type     = light_armor
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 28 }
      name     = "84. Mech/188. Strelkovaya Diviziya"
      strength = 80
      type     = motorized
      extra    = engineer
    }
  }
  landunit =
  { id       = { type = 10848 id = 29 }
    name     = "27ya Armiya"
    location = 272
    division =
    { id       = { type = 10848 id = 30 }
      name     = "180. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 31 }
      name     = "181. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 32 }
      name     = "182. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 33 }
      name     = "16. 'Ul'yanovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 34 }
      name     = "3. 'Tihookeanskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 35 }
      name     = "22. 'Krasnodarskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 36 }
    name     = "47ya Armiya Corps"
    location = 240
    division =
    { id       = { type = 10848 id = 37 }
      name     = "143. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 38 }
      name     = "121. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 39 }
      name     = "55. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 40 }
    name     = "17th Mechanized Corps"
    location = 175
    division =
    { id       = { type = 10848 id = 41 }
      name     = "210. Motorizovannaya Diviziya"
      strength = 60
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 42 }
    name     = "4ya Armiya"
    location = 237
    division =
    { id       = { type = 10848 id = 43 }
      name     = "6. 'Orlovskaya' Strelk. Div."
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 44 }
      name     = "42. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 45 }
      name     = "49. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 46 }
      name     = "205. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 47 }
    name     = "3ya Armiya"
    location = 238
    division =
    { id       = { type = 10848 id = 48 }
      name     = "27. 'Omskaya' Strelk. Div."
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 49 }
      name     = "50. 'Tamanskaya' Strelk. Div."
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 50 }
      name     = "24. 'Samaro-Ul'yanov.' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 51 }
      name     = "17. 'Gor'kovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 52 }
      name     = "56. 'Moskovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 53 }
      name     = "85. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 54 }
    name     = "10ya Armiya"
    location = 236
    division =
    { id       = { type = 10848 id = 55 }
      name     = "86. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 56 }
      name     = "13. 'Dagestanskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 57 }
      name     = "2. 'Belorusskaya' Strelk. Div."
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 58 }
      name     = "113. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 59 }
      name     = "6. 'Chongarskaya' Kav. Div."
      strength = 80
      type     = cavalry
    }
    division =
    { id       = { type = 10848 id = 60 }
      name     = "8. 'Minskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 61 }
      name     = "4. Tankovaya Diviziya"
      strength = 80
      type     = light_armor
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 62 }
      name     = "29. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
    }
  }
  landunit =
  { id       = { type = 10848 id = 63 }
    name     = "13ya Armiya"
    location = 234
    division =
    { id       = { type = 10848 id = 64 }
      name     = "161. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 65 }
      name     = "100. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 66 }
    name     = "31ya Armiya Corps"
    location = 253
    division =
    { id       = { type = 10848 id = 67 }
      name     = "193. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 68 }
      name     = "195. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 69 }
      name     = "200. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 70 }
    name     = "36ya Armiya Corps"
    location = 1848
    division =
    { id       = { type = 10848 id = 71 }
      name     = "140. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 72 }
      name     = "146. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 73 }
      name     = "228. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 74 }
    name     = "49ya Armiya Corps"
    location = 1850
    division =
    { id       = { type = 10848 id = 75 }
      name     = "199. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 76 }
      name     = "197. 'Kievskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 77 }
      name     = "190. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 78 }
    name     = "55ya Armiya Corps"
    location = 1857
    division =
    { id       = { type = 10848 id = 79 }
      name     = "189. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 80 }
      name     = "169. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 81 }
      name     = "130. Strelkovaya Diviziya"
      strength = 70
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 82 }
    name     = "15. Mechanized Corps"
    location = 1370
    division =
    { id       = { type = 10848 id = 83 }
      name     = "212. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 84 }
    name     = "24. Mechanized Corps"
    location = 1520
    division =
    { id       = { type = 10848 id = 85 }
      name     = "213. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 86 }
    name     = "5ya Armiya"
    location = 1368
    division =
    { id       = { type = 10848 id = 87 }
      name     = "45. 'Volynskaya' Strelk. Div."
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 88 }
      name     = "87. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 89 }
      name     = "62. 'Turkestanskaya' Strelk. Div."
      strength = 80
      type     = infantry
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10848 id = 90 }
    name     = "6ya Armiya"
    location = 1372
    division =
    { id       = { type = 10848 id = 91 }
      name     = "159. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 92 }
      name     = "139. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 93 }
      name     = "141. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 94 }
      name     = "3. 'Bessarabskaya' Kav. Div."
      strength = 80
      type     = cavalry
    }
    division =
    { id       = { type = 10848 id = 95 }
      name     = "81. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 96 }
    name     = "12ya Armiya"
    location = 258
    division =
    { id       = { type = 10848 id = 97 }
      name     = "164. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 98 }
      name     = "60. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 99 }
      name     = "69. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
  }
  landunit =
  { id       = { type = 10848 id = 100 }
    name     = "26ya Armiya"
    location = 133
    division =
    { id       = { type = 10848 id = 101 }
      name     = "99. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 103 }
      name     = "173. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 102 }
      name     = "240./7. Motorizovannaya Diviziya"
      strength = 60
      type     = motorized
    }
  }
  landunit =
  { id       = { type = 10848 id = 104 }
    name     = "7ya Armiya Corps"
    location = 260
    division =
    { id       = { type = 10848 id = 105 }
      name     = "116. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 107 }
      name     = "196. 'Dnepropetrov.' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 106 }
      name     = "206. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 108 }
    name     = "9ya Armiya Corps"
    location = 247
    division =
    { id       = { type = 10848 id = 110 }
      name     = "106. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 111 }
      name     = "156. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 112 }
      name     = "47. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 109 }
      name     = "32. Kavaleriyskaya Diviziya"
      strength = 30
      type     = cavalry
    }
  }
  landunit =
  { id       = { type = 10848 id = 113 }
    name     = "9ya Armiya"
    location = 243
    division =
    { id       = { type = 10848 id = 114 }
      name     = "176. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 115 }
      name     = "25. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 116 }
      name     = "74. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 117 }
      name     = "51. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 118 }
      name     = "95. 'Moldavskaya' Strelk. Div."
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 119 }
      name     = "9. 'Krymskaya' Kav. Div."
      strength = 80
      type     = cavalry
    }
    division =
    { id       = { type = 10848 id = 120 }
      name     = "15. Motorizovannaya Diviziya"
      strength = 80
      type     = motorized
    }
  }
  landunit =
  { id       = { type = 10848 id = 121 }
    name     = "Transcaucasus Military District"
    location = 1907
    division =
    { id       = { type = 10848 id = 122 }
      name     = "136. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 123 }
      name     = "138. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 124 }
      name     = "47. Strelkovaya Diviziya"
      strength = 80
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 125 }
      name     = "17. 'Gor'kovskaya' Strelk. Div."
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 126 }
      name     = "63. Strelkovaya Diviziya"
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 127 }
      name     = "24. Kavaleriyskaya Diviziya"
      strength = 30
      type     = cavalry
    }
  }
  landunit =
  { id       = { type = 10848 id = 129 }
    name     = "28. Mechanized Corps"
    location = 277
    division =
    { id       = { type = 10848 id = 128 }
      name     = "6. Tankovaya Diviziya"
      strength = 90
      type     = light_armor
      model    = 0
    }
  }
  landunit =
  { id       = { type = 10848 id = 130 }
    name     = "Arkhangelsk Military District"
    location = 153
    division =
    { id       = { type = 10848 id = 131 }
      name     = "88. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10848 id = 132 }
    name     = "Moscow Military District"
    location = 175
    division =
    { id       = { type = 10848 id = 133 }
      name     = "STAVKA"
      strength = 100
      type     = hq
    }
    division =
    { id       = { type = 10848 id = 134 }
      name     = "118. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = engineer
    }
    division =
    { id       = { type = 10848 id = 135 }
      name     = "235. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = engineer
    }
  }
  landunit =
  { id       = { type = 10848 id = 136 }
    name     = "North Caucasus Military District"
    location = 1845
    division =
    { id       = { type = 10848 id = 137 }
      name     = "157. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 138 }
      name     = "28. Strelkovaya Diviziya"
      strength = 30
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 139 }
      name     = "203. Motostrelkovaya Diviziya"
      strength = 60
      type     = motorized
    }
  }
  landunit =
  { id       = { type = 10848 id = 140 }
    name     = "Orel Military District"
    location = 285
    division =
    { id       = { type = 10848 id = 144 }
      name     = "19. 'Voronezhskaya' Strelk. Div."
      strength = 100
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 142 }
      name     = "89. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 143 }
      name     = "217. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 141 }
      name     = "120. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 147 }
    name     = "Central Asia Military District"
    location = 1556
    division =
    { id       = { type = 10848 id = 145 }
      name     = "68./83./194. Strelkovaya Diviziya"
      strength = 100
      type     = bergsjaeger
    }
    division =
    { id       = { type = 10848 id = 146 }
      name     = "21. 'Permskaya' Strelk. Div."
      strength = 100
      type     = bergsjaeger
    }
  }
  landunit =
  { id       = { type = 10848 id = 149 }
    name     = "Transbaikal Military District"
    location = 1520
    division =
    { id       = { type = 10848 id = 150 }
      name     = "65. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 148 }
      name     = "114. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 151 }
      name     = "93. 'Vostochno-Sibir.' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 152 }
      name     = "94. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
  }
  landunit =
  { id       = { type = 10848 id = 153 }
    name     = "17ya Armiya"
    location = 1907
    division =
    { id       = { type = 10848 id = 154 }
      name     = "82. Motorized Division"
      strength = 100
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 155 }
    name     = "1ya Armiya"
    location = 1383
    division =
    { id       = { type = 10848 id = 156 }
      name     = "39. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 157 }
      name     = "26. 'Zlatoustovskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 158 }
      name     = "21. 'Permskaya' Strelk. Div."
      strength = 100
      type     = infantry
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10848 id = 159 }
    name     = "21ya Armiya"
    location = 1528
    division =
    { id       = { type = 10848 id = 160 }
      name     = "59. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
      extra    = artillery
    }
    division =
    { id       = { type = 10848 id = 161 }
      name     = "22. 'Krasnodarskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 162 }
      name     = "1. Strelkovaya Diviziya"
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 163 }
      name     = "4. 'Smolenskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 164 }
      name     = "5. 'Vitebskaya' Strelk. Div."
      strength = 100
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 165 }
      name     = "239. Motostrelkovaya Diviziya"
      strength = 30
      type     = motorized
      extra    = anti_tank
    }
  }
  landunit =
  { id       = { type = 10848 id = 166 }
    name     = "Special Forces Far East"
    location = 1523
    division =
    { id       = { type = 10848 id = 167 }
      name     = "35. 'Sibirskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 168 }
      name     = "66. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 169 }
      name     = "101. Strelkovaya Diviziya"
      strength = 30
      type     = bergsjaeger
    }
  }
  landunit =
  { id       = { type = 10848 id = 170 }
    name     = "2ya Armiya"
    location = 1827
    division =
    { id       = { type = 10848 id = 171 }
      name     = "12. Strelkovaya Diviziya"
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 172 }
      name     = "3. 'Tihookeanskaya' Strelk. Div."
      strength = 80
      type     = infantry
      extra    = artillery
    }
  }
  landunit =
  { id       = { type = 10848 id = 173 }
    name     = "25ya Armiya"
    location = 1570
    division =
    { id            = { type = 10848 id = 174 }
      name          = "92. Strelkovaya Diviziya"
      strength      = 80
      type          = infantry
      extra         = artillery
      brigade_model = 2
    }
    division =
    { id       = { type = 10848 id = 175 }
      name     = "32. 'Saratovskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
    division =
    { id       = { type = 10848 id = 176 }
      name     = "40. 'Bogucharskaya' Strelk. Div."
      strength = 80
      type     = infantry
    }
  }
  # ################################
	### Soviet Navy OOB ###
  # ################################
  navalunit =
  { id       = { type = 10848 id = 177 }
    name     = "Arskoje Flote"
    location = 133 # Murmansk
    base     = 133
    division =
    { id    = { type = 10848 id = 178 }
      name  = "1. Flotiliya Esmintsev"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10848 id = 179 }
      name  = "1. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 180 }
      name  = "2. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 181 }
      name  = "18. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 182 }
      name  = "19. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 183 }
      name  = "20. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { id       = { type = 10848 id = 184 }
    name     = "CCCP Baltijskoje Flote"
    location = 187 # Leningrad
    base     = 187
    division =
    { id    = { type = 10848 id = 185 }
      name  = "Marat"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 10848 id = 186 }
      name  = "Oktyabrskaya Revoluciya"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 10848 id = 187 }
      name  = "4. Flotiliya Esmintsev"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10848 id = 188 }
      name  = "3. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 189 }
      name  = "4. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 190 }
      name  = "5. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 191 }
      name  = "6. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 192 }
      name  = "7. Flotiliya Podlodok"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 10848 id = 193 }
      name  = "21. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 194 }
      name  = "22. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 195 }
      name  = "23. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { id       = { type = 10848 id = 196 }
    name     = "Cernoje Flote"
    location = 253 # Sevastopol
    base     = 253
    division =
    { id    = { type = 10848 id = 197 }
      name  = "Parishskaya Kommuna"
      type  = battleship
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      extra4 = none
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 10848 id = 198 }
      name  = "Krasni Kavkaz"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_anti_air_l
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 10848 id = 200 }
      name  = "Profintern"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 10848 id = 201 }
      name  = "Komintern"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 10848 id = 202 }
      name  = "Chervonaya Ukraina"
      type  = light_cruiser
      model = 0
      extra1 = naval_anti_air_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 10848 id = 203 }
      name  = "5. Flotiliya Esmintsev"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10848 id = 204 }
      name  = "11. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 205 }
      name  = "24. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 206 }
      name  = "25. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { id       = { type = 10848 id = 207 }
    name     = "Beringovo Flote"
    location = 1372 # Vladivostok
    base     = 1372
    division =
    { id    = { type = 10848 id = 208 }
      name  = "7. Flotiliya Esmintsev"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10848 id = 209 }
      name  = "12. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10848 id = 210 }
      name  = "13. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10848 id = 211 }
      name  = "14. Flotiliya Podlodok"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 10848 id = 212 }
      name  = "17. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 10848 id = 213 }
      name  = "26. Flotiliya Podlodok"
      type  = submarine
      model = 0
    }
    division =
    { id   = { type = 10848 id = 199 }
      name = "1. Transportnaya Flotiliya"
      type = transport
    }
  }
	### USSR Air OOB ###
  airunit =
  { id       = { type = 10848 id = 215 }
    name     = "Leningrad I. AD"
    location = 187
    base     = 187
    division =
    { id       = { type = 10848 id = 216 }
      name     = "1. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 217 }
      name     = "2. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10848 id = 218 }
    name     = "Riga II. AD"
    location = 201
    base     = 201
    division =
    { id       = { type = 10848 id = 219 }
      name     = "4. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10848 id = 220 }
    name     = "III. AD"
    location = 220
    base     = 220
    division =
    { id       = { type = 10848 id = 221 }
      name     = "12. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 222 }
      name     = "13. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 223 }
      name     = "9. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 224 }
      name     = "10. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10848 id = 225 }
    name     = "Kiev IV. AD"
    location = 238
    base     = 238
    division =
    { id       = { type = 10848 id = 226 }
      name     = "14. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10848 id = 227 }
    name     = "Mockba v. AD"
    location = 175
    base     = 175
    division =
    { id       = { type = 10848 id = 228 }
      name     = "6. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10848 id = 229 }
    name     = "Transbaikal VI. AD"
    location = 1372
    base     = 1372
    division =
    { id       = { type = 10848 id = 230 }
      name     = "30. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 0
    }
  }
  airunit =
  { id       = { type = 10848 id = 231 }
    name     = "Kamchatski VII. AD"
    location = 1525
    base     = 1525
    division =
    { id       = { type = 10848 id = 232 }
      name     = "29. IAD"
      strength = 100
      type     = interceptor
      model    = 0
    }
    division =
    { id       = { type = 10848 id = 214 }
      name     = "33. BAD"
      strength = 100
      type     = tactical_bomber
      model    = 0
    }
  }
	### Development ###
	convoy = { 
		id = { type = 10848 id = 236 } 
		istradeconvoy = no 
		transports = 5 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = yes 
		supplies = no 
		path = { 1175 2216 1367 } 
		} 
	province_development = { 
		id = { type = 10848 id = 237 } 
		name = "" 
		progress = 0.0000 
		location = 175 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = september 
			day = 1 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 26 
		done = 0 
		days = 2405 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 244 } 
		name = "" 
		progress = 0.0000 
		location = 236 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 245 } 
		name = "" 
		progress = 0.0000 
		location = 1907 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 248 } 
		name = "" 
		progress = 0.0000 
		location = 1578 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 252 } 
		name = "" 
		progress = 0.0000 
		location = 249 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 254 } 
		name = "" 
		progress = 0.0000 
		location = 187 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = march 
			day = 1 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2226 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 255 } 
		name = "" 
		progress = 0.0000 
		location = 243 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 256 } 
		name = "" 
		progress = 0.0000 
		location = 238 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = september 
			day = 1 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 26 
		done = 0 
		days = 2405 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 260 } 
		name = "" 
		progress = 0.0000 
		location = 228 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 261 } 
		name = "" 
		progress = 0.0000 
		location = 235 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 262 } 
		name = "" 
		progress = 0.0000 
		location = 1828 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 264 } 
		name = "" 
		progress = 0.0000 
		location = 248 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 265 } 
		name = "" 
		progress = 0.0000 
		location = 258 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 266 } 
		name = "" 
		progress = 0.0000 
		location = 212 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 267 } 
		name = "" 
		progress = 0.0000 
		location = 256 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 268 } 
		name = "" 
		progress = 0.0000 
		location = 1780 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 269 } 
		name = "" 
		progress = 0.0000 
		location = 283 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 270 } 
		name = "" 
		progress = 0.0000 
		location = 233 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = march 
			day = 1 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2226 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 271 } 
		name = "" 
		progress = 0.0000 
		location = 234 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 273 } 
		name = "" 
		progress = 0.0000 
		location = 1547 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 272 } 
		name = "" 
		progress = 0.0000 
		location = 1832 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 277 } 
		name = "" 
		progress = 0.0000 
		location = 246 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 278 } 
		name = "" 
		progress = 0.0000 
		location = 182 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 279 } 
		name = "" 
		progress = 0.0000 
		location = 94 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 280 } 
		name = "" 
		progress = 0.0000 
		location = 1570 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 292 } 
		name = "" 
		progress = 0.0000 
		location = 1560 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 294 } 
		name = "" 
		progress = 0.0000 
		location = 1561 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 298 } 
		name = "" 
		progress = 0.0000 
		location = 1575 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 299 } 
		name = "" 
		progress = 0.0000 
		location = 1552 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 300 } 
		name = "" 
		progress = 0.0000 
		location = 1550 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = march 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 238 } 
		name = "" 
		progress = 0.0000 
		location = 1850 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 239 } 
		name = "" 
		progress = 0.0000 
		location = 1422 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 240 } 
		name = "" 
		progress = 0.0000 
		location = 1856 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 241 } 
		name = "" 
		progress = 0.0000 
		location = 1429 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 247 } 
		name = "" 
		progress = 0.0000 
		location = 1424 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 258 } 
		name = "" 
		progress = 0.0000 
		location = 1844 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 274 } 
		name = "" 
		progress = 0.0000 
		location = 1546 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 143 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 293 } 
		name = "" 
		progress = 0.0000 
		location = 1554 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 301 } 
		name = "" 
		progress = 0.0000 
		location = 1576 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 115 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 296 } 
		name = "" 
		progress = 0.0000 
		location = 1428 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 297 } 
		name = "" 
		progress = 0.0000 
		location = 1149 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = october 
			day = 8 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2945 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 242 } 
		name = "" 
		progress = 0.0000 
		location = 1485 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 243 } 
		name = "" 
		progress = 0.0000 
		location = 1490 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 246 } 
		name = "" 
		progress = 0.0000 
		location = 1151 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 230 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 249 } 
		name = "" 
		progress = 0.0000 
		location = 1572 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 250 } 
		name = "" 
		progress = 0.0000 
		location = 1427 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 251 } 
		name = "" 
		progress = 0.0000 
		location = 1548 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 253 } 
		name = "" 
		progress = 0.0000 
		location = 1567 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 257 } 
		name = "" 
		progress = 0.0000 
		location = 168 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 230 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 259 } 
		name = "" 
		progress = 0.0000 
		location = 1847 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 263 } 
		name = "" 
		progress = 0.0000 
		location = 1574 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 275 } 
		name = "" 
		progress = 0.0000 
		location = 1150 
		cost = 2.0000 
		date = { 
			year = 1946 
			month = february 
			day = 19 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 230 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 276 } 
		name = "" 
		progress = 0.0000 
		location = 1566 
		cost = 2.0000 
		date = { 
			year = 1943 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 295 } 
		name = "" 
		progress = 0.0000 
		location = 1367 
		cost = 2.0000 
		date = { 
			year = 1948 
			month = august 
			day = 23 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2585 
		days_for_first = 287 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 10848 id = 281 } 
		name = "" 
		progress = 0.0000 
		location = 175 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = october 
			day = 16 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3456 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 282 } 
		name = "" 
		progress = 0.0000 
		location = 1151 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = october 
			day = 16 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3456 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 283 } 
		name = "" 
		progress = 0.0000 
		location = 1578 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = october 
			day = 16 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3456 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 284 } 
		name = "" 
		progress = 0.0000 
		location = 1424 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = october 
			day = 16 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3456 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 285 } 
		name = "" 
		progress = 0.0000 
		location = 1572 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 286 } 
		name = "" 
		progress = 0.0000 
		location = 249 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 287 } 
		name = "" 
		progress = 0.0000 
		location = 236 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 288 } 
		name = "" 
		progress = 0.0000 
		location = 243 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 289 } 
		name = "" 
		progress = 0.0000 
		location = 1907 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 290 } 
		name = "" 
		progress = 0.0000 
		location = 1567 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 291 } 
		name = "" 
		progress = 0.0000 
		location = 1427 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = october 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 6 
		done = 0 
		days = 2074 
		days_for_first = 346 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 10848 id = 302 } 
		name = "" 
		progress = 0.0000 
		location = 1587 
		cost = 20.0000 
		date = { 
			year = 1937 
			month = may 
			day = 13 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 492 
		days_for_first = 173 
		gearing_bonus = 0.0000 
		type = rocket_test 
		} 
	province_development = { 
		id = { type = 10848 id = 304 } 
		name = "" 
		progress = 0.0000 
		location = 189 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 305 } 
		name = "" 
		progress = 0.0000 
		location = 190 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 306 } 
		name = "" 
		progress = 0.0000 
		location = 288 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 307 } 
		name = "" 
		progress = 0.0000 
		location = 182 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 308 } 
		name = "" 
		progress = 0.0000 
		location = 94 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 309 } 
		name = "" 
		progress = 0.0000 
		location = 238 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 310 } 
		name = "" 
		progress = 0.0000 
		location = 258 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 311 } 
		name = "" 
		progress = 0.0000 
		location = 248 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 312 } 
		name = "" 
		progress = 0.0000 
		location = 243 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 313 } 
		name = "" 
		progress = 0.0000 
		location = 181 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 10848 id = 314 } 
		name = "" 
		progress = 0.0000 
		location = 233 
		cost = 5.0000 
		date = { 
			year = 1938 
			month = october 
			day = 20 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 2 
		done = 0 
		days = 518 
		days_for_first = 518 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	division_development = { 
		id = { type = 10848 id = 233 } 
		name = "8. Flotiliya Esmintsev" 
		progress = 0.0000 
		location = 0 
		cost = 3.6480 
		date = { 
			year = 1936 
			month = april 
			day = 1 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.2018 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 114 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 10848 id = 234 } 
		name = "29. Flotiliya Podlodok" 
		progress = 0.0000 
		location = 0 
		cost = 1.9200 
		date = { 
			year = 1936 
			month = february 
			day = 0 
			hour = 0 
			} 
		manpower = 0.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7170 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 10848 id = 235 } 
		name = "30. Flotiliya Podlodok" 
		progress = 0.0000 
		location = 0 
		cost = 1.9200 
		date = { 
			year = 1936 
			month = march 
			day = 1 
			hour = 0 
			} 
		manpower = 0.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.4245 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 106 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 10848 id = 303 } 
		name = "Moscow Front" 
		progress = 0.0000 
		location = 175 
		cost = 15.9685 
		date = { 
			year = 1939 
			month = march 
			day = 26 
			hour = 0 
			} 
		manpower = 7.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		retooling_time = 1.0000 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 1166 
		days_for_first = 259 
		gearing_bonus = 0.0000 
		type = hq 
		extra = anti_air 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 0 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		}
}
