
##############################
# Country definition for ENG #
##############################

province =
{ id         = 5
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Scapa Flow
province =
{ id       = 9
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Glasgow
province =
{ id         = 13
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Sheffield
province =
{ id         = 14
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Liverpool
province = { id = 16 anti_air = 2 } # Birmingham
province =
{ id         = 17
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Norwich
province = { id = 19 anti_air = 3 } # London
province =
{ id          = 20
  anti_air    = 5
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 3
}               # Dover
province =
{ id         = 21
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Portsmouth
province =
{ id         = 23
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Plymouth
province = { id = 28 oilpool = 200 supplypool = 200 } # Belfast # was 2000 supplies + 1000 oil before 1.09
province =
{ id          = 31
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 5 current_size = 5 }
  coastalfort = 1
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 1000 before 1.09
}               # Malta
province =
{ id          = 348
  anti_air    = 6
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 6
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 1000 before 1.09
}               # Gibraltar
province =
{ id       = 444
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cyprus
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id         = 576
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
  metalpool  = 13
  supplypool = 1
}              # Newfoundland
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Andros
province =
{ id         = 866
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  oilpool    = 100
  supplypool = 200
}              # Falkland Islands
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  metalpool  = 46
  supplypool = 1
}            # Georgetown
province = { id = 900 anti_air = 2 } # Suez
province = { id = 901 anti_air = 2 metalpool = 22 oilpool = 800 supplypool = 800 } # Port Said  # was 2000 supplies + 1000 oil before 1.09
province = { id = 903 anti_air = 2 } # Cairo
province =
{ id         = 906
  anti_air   = 5
  air_base   = { size = 7 current_size = 7 }
  naval_base = { size = 10 current_size = 10 }
}              # Alexandria
province =
{ id         = 988
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 200 # was 1000 before 1.09
  supplypool = 200 # was 2000 before 1.09
}              # Freetown
province =
{ id       = 1002
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Accra
province =
{ id       = 1008
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  metalpool  = 18
}            # Lagos
province =
{ id       = 1061
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 1066
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Khartoum
province =
{ id       = 1296
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id         = 1299
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rangoon
province =
{ id          = 1315
  anti_air    = 4
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 1
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 1000 before 1.09
}               # Hong Kong
province =
{ id          = 1353
  anti_air    = 6
  air_base    = { size = 8 current_size = 8 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 3
  rarematerialspool = 120
  metalpool = 80
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 2000 before 1.09
}               # Singapore
province =
{ id       = 1457
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Calcutta
province =
{ id       = 1467
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Indore
province =
{ id       = 1469
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province =
{ id         = 1494
  anti_air   = 1
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 8 current_size = 8 }
}              # Karachi
province =
{ id         = 1505
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 200 # was 1000 before 1.09
  supplypool = 400 # was 2000 before 1.09
}              # Bombay
province =
{ id       = 1514
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cochin
province =
{ id         = 1516
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # Trincomalee
province =
{ id          = 1517
  anti_air    = 2
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 3
  rarematerialspool = 68
  oilpool     = 200 # was 1000 before 1.09
  supplypool  = 200 # was 2000 before 1.09
}               # Colombo
province =
{ id       = 1644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  supplypool  = 5
}            # Kuching
province = { id = 1797 anti_air = 1 } # Jerusalem
province =
{ id         = 1798
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Tel Aviv
province =
{ id         = 1813
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # Aden
province =
{ id         = 1817
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 100
  supplypool = 200
}              # Diego Garcia Island

#####################
# Country main data #
#####################

country =
{ tag                    = ENG
  peacetime_ic_mod       = 0.9
  capital                = 19
  manpower               = 887.7 # 750 + 163.6 from garrisons - building queue
  # Resource Reserves
  energy                 = 1000
  metal                  = 821
  rare_materials         = 312
  oil                    = 7100
  supplies               = 12893
  money                  = 70
  consumer = 0.1650 
  supply = 0.0884 
  production = 0.7466 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  transports             = 597
  escorts                = 150
  diplomacy =
  { relation =
    { tag        = AFG
      value      = -75
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = ARG value = 75 }
	relation = { tag = ALB value = 3 }
    relation = { tag = AST value = 200 } # was access = yes 
    relation =
    { tag        = AUS
      value      = 75
      guaranteed = { day = 27 month = september year = 1934 }
    }
    relation = { tag = BEL value = 150 }
    relation = { tag = BHU value = 200 access = yes }
    relation = { tag = BUL value = 20 }
    relation = { tag = CAN value = 200 } # was access = yes
    relation = { tag = CUB value = 30 }
    relation = { tag = CZE value = 125 }
    relation =
    { tag        = DEN
      value      = 100
      guaranteed = { day = 30 month = august year = 1934 }
    }
    relation = { tag = ENG value = 50 }
    relation = { tag = EST value = 65 }
    relation = { tag = ETH value = 50 }
    relation = { tag = FIN value = 85 }
    relation = { tag = FRA value = 150 }
    relation = { tag = GER value = 1 }
    relation =
    { tag        = GRE
      value      = 50
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = GUA value = 50 }
    relation = { tag = HOL value = 125 }
    relation = { tag = LUX value = 28 }
	relation = { tag = HON value = 50 }
    relation = { tag = HUN value = -50 }
    relation =
    { tag        = IRE
      value      = 25
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = IRQ
      value      = 100
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = ITA value = -50 }
    relation = { tag = JAP value = -25 }
    relation = { tag = LAT value = 65 }
    relation = { tag = LIT value = 65 }
    relation = { tag = MEX value = 50 }
    relation = { tag = NEP value = 200 access = yes }
    relation =
    { tag        = NOR
      value      = 90
      guaranteed = { day = 30 month = august year = 1934 }
    }
    relation = { tag = NZL value = 200 } # was access = yes
    relation =
    { tag        = OMN
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = PER
      value      = 25
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = POL value = 50 }
    relation =
    { tag        = POR
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = ROM value = 50 }
    relation = { tag = SAF value = 200 } # was access = yes
    relation =
    { tag        = SAU
      value      = 100
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation =
    { tag        = SCH
      value      = 50
      guaranteed = { day = 16 month = may year = 1935 }
    }
    relation = { tag = SIA value = 70 }
    relation = { tag = SPR value = -10 }
    relation = { tag = SOV value = -25 }
    relation =
    { tag        = SWE
      value      = 80
      guaranteed = { day = 30 month = august year = 1934 }
    }
    relation =
    { tag        = TUR
      value      = 75
      guaranteed = { day = 11 month = february year = 1934 }
    }
    relation = { tag = USA value = 150 }
    relation = { tag = VEN value = -10 }
    relation =
    { tag        = YEM
      value      = 150
      access     = yes
      guaranteed = { day = 11 month = february year = 1934 }
    }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 5 }
  SpyInfo                = { country = "GER" NumberOfSpies = 3 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 4 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 2 }
  SpyInfo                = { country = "CZE" NumberOfSpies = 2 }
  SpyInfo                = { country = "AUS" NumberOfSpies = 1 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 2 }
  SpyInfo                = { country = "POL" NumberOfSpies = 3 }
  SpyInfo                = { country = "SWE" NumberOfSpies = 1 }
  SpyInfo                = { country = "NOR" NumberOfSpies = 5 }
  SpyInfo                = { country = "FIN" NumberOfSpies = 2 }
  SpyInfo                = { country = "YUG" NumberOfSpies = 3 }
  SpyInfo                = { country = "HUN" NumberOfSpies = 2 }
  SpyInfo                = { country = "BUL" NumberOfSpies = 2 }
  SpyInfo                = { country = "BEL" NumberOfSpies = 3 }
  SpyInfo                = { country = "DEN" NumberOfSpies = 1 }
  SpyInfo                = { country = "HOL" NumberOfSpies = 3 }
  SpyInfo                = { country = "USA" NumberOfSpies = 4 }
  SpyInfo                = { country = "ALB" NumberOfSpies = 1 }
  SpyInfo                = { country = "GRE" NumberOfSpies = 1 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 1 }
  SpyInfo                = { country = "BRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 1 }
  SpyInfo                = { country = "ROM" NumberOfSpies = 2 }
  SpyInfo                = { country = "LIT" NumberOfSpies = 2 }
  SpyInfo                = { country = "LUX" NumberOfSpies = 1 }
  SpyInfo                = { country = "POR" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 2 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 4 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 1 }
  SpyInfo                = { country = "AST" NumberOfSpies = 2 }
  SpyInfo                = { country = "NZL" NumberOfSpies = 2 }
  SpyInfo                = { country = "CAN" NumberOfSpies = 2 }
  SpyInfo                = { country = "IRE" NumberOfSpies = 4 }
  SpyInfo                = { country = "IRQ" NumberOfSpies = 3 }
  SpyInfo                = { country = "BHU" NumberOfSpies = 1 }
  SpyInfo                = { country = "YEM" NumberOfSpies = 1 }
  SpyInfo                = { country = "ETH" NumberOfSpies = 1 }
  # GREAT BRITAIN
  nationalprovinces      = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   1494
                             1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459 1457
                             1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288 1289
                             1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1300 1292 1454 1297 1878 1877 444 
                           }
  # GREAT BRITAIN
  ownedprovinces         = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444 
                             1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
                             1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
                             1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1300 1292 1454 1297 1878 1877 1799 1797 1796 404  1802 1803
                             406  407  1813 1814 1820 1822 1504 1798 900  901  902  903  904  905  906  907  908  909  910  911  912  913  914  915 
                             4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041
                             1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666 
                             668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1112 1111 1105
                             1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  1622 1683 1684
                             1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 575  576  1614 1611
                           }
  # GREAT BRITAIN
  controlledprovinces    = { 3    5    6    7    8    9    10   11   12   13   14   15   16   17   19   20   21   22   23   28   29   348  31   444 
                             1494 1481 1480 1465 1466 1479 1482 1483 1475 1476 1478 1477 1469 1470 1471 1472 1456 1468 1467 1464 1463 1474 1460 1459
                             1457 1458 1461 1508 1462 1505 1506 1507 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1284 1285 1286 1287 1288
                             1289 1290 1291 1898 1304 1295 1296 1301 1302 1346 1299 1298 1300 1292 1454 1297 1878 1877 1799 1797 1796 404  1802 1803
                             406  407  1813 1814 1820 1822 1504 1798 900  901  902  903  904  905  906  907  908  909  910  911  912  913  914  915 
                             4    1020 1019 1021 1022 1027 1023 1026 1024 1025 1800 1801 1065 1066 1069 1068 1067 1029 1028 1032 1031 1030 1040 1041
                             1349 1350 1351 1352 1353 1644 1646 1647 1315 758  891  871  873  806  807  808  809  897  538  652  653  664  665  666 
                             668  805  896  866  1147 1148 1816 1817 1136 1815 1132 1139 1062 1140 1141 1064 1060 1061 1059 1035 1036 1112 1111 1105
                             1124 1125 1104 1099 1129 1126 1128 1000 1001 1002 1008 1007 999  1009 1010 1011 1145 1085 1012 988  982  1622 1683 1684
                             1685 1686 1763 1761 1767 1768 1769 1770 1757 1759 1760 1752 1753 1754 1755 1758 575  576  1614 1611
                           }
  # Commonwealth Tech '36
  # UK 1936 techs
  # ######################
  techapps               = { 4010  4020  4120  4130  2150  2010  2020  2030  2290  2300  2310  2450  2460  2510  1010  1020  1190  1200  1210  1220 
                             4220  1110  2400  1150  1310  5010  5020  5050  5080  5090  5190  5200  5310  5320  5410  5470  5480  3420  9010  9020 
                             9030  9140  6010  6030  6110  6120  8010  8020  8030  8040  8050  8070  8100  8120  3010  3020  3030  3070  3080  3090 
                             12100 12110 3100  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280  3320  3330  3340  3400  3410  14000 3470
                             1380
                           }
  blueprints             = { 1150 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 8
    professional_army = 7
    defense_lobby     = 6
    interventionism   = 6
  }
  headofstate            = { type = 9 id = 1001 }
  headofgovernment       = { type = 9 id = 1002 }
  foreignminister        = { type = 9 id = 1003 }
  armamentminister       = { type = 9 id = 1004 }
  ministerofsecurity     = { type = 9 id = 1005 }
  ministerofintelligence = { type = 9 id = 1006 }
  chiefofstaff           = { type = 9 id = 1007 }
  chiefofarmy            = { type = 9 id = 1008 }
  chiefofnavy            = { type = 9 id = 1009 }
  chiefofair             = { type = 9 id = 1010 }

  nationalidentity = "policy_identity_imperial" 
	socialpolicy = "policy_social_liberal" 
	nationalculture = "policy_culture_libertarian"

 ################################################
	### United Kingdom Land OOB ###
 ################################################
  landunit =
  { name     = "Aldershot Command"
    location = 22
    id       = { type = 12700 id = 1 }
    division =
    { id       = { type = 12700 id = 63 }
      name     = "British Army HQ"
      type     = hq
      model    = 0
      strength = 100
    }
    division =
    { id            = { type = 12700 id = 2 }
      name          = "1st Infantry Division"
      type          = infantry
      extra         = artillery
      brigade_model = 2
      strength      = 100
    }
    division =
    { id       = { type = 12700 id = 3 }
      name     = "2nd Infantry Division"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Northern Command"
    location = 10
    id       = { type = 12700 id = 4 }
    division =
    { id       = { type = 12700 id = 5 }
      name     = "5th Infantry Division"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Southern Command"
    location = 21
    id       = { type = 12700 id = 6 }
    division =
    { id       = { type = 12700 id = 7 }
      name     = "3rd Infantry Division"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Hong Kong Command"
    location = 1315
    id       = { type = 12700 id = 8 }
    division =
    { id       = { type = 12700 id = 9 }
      name     = "Hong Kong Defence Force"
      type     = garrison
      strength = 25 # was 100 before 1.11
      locked   = yes
    }
  }
  landunit =
  { name     = "Singapore Command"
    location = 1353
    id       = { type = 12700 id = 10 }
    division =
    { id       = { type = 12700 id = 11 }
      name     = "Singapore Defence Force"
      type     = garrison
      strength = 25 # was 100 before 1.11
      locked   = yes
    }
  }
  landunit =
  { name     = "Gibraltar Command"
    location = 348
    id       = { type = 12700 id = 12 }
    division =
    { id       = { type = 12700 id = 13 }
      name     = "Gibraltar Defence Force"
      type     = garrison
      strength = 25 # was 100 before 1.11
      locked   = yes
    }
  }
  landunit =
  { name     = "Ceylon Command"
    location = 1517
    id       = { type = 12700 id = 14 }
    division =
    { id       = { type = 12700 id = 15 }
      name     = "Ceylon Defence Force"
      type     = garrison
      strength = 25 # was 100 before 1.11
      locked   = yes
    }
  }
  landunit =
  { name     = "Malta Command"
    location = 31
    id       = { type = 12700 id = 16 }
    division =
    { id       = { type = 12700 id = 17 }
      name     = "Malta Defence Force"
      type     = garrison
      strength = 25 # was 100 before 1.11
      locked   = yes
    }
  }
  landunit =
  { name     = "Middle East Command"
    location = 1797
    id       = { type = 12700 id = 18 }
    division =
    { id       = { type = 12700 id = 19 }
      name     = "7th Infantry Division"
      type     = infantry
      strength = 100
    }
    division =
    { id       = { type = 12700 id = 20 }
      name     = "8th Infantry Division"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "British Indian Army"
    location = 1469 # Delhi
    id       = { type = 12700 id = 21 }
    division =
    { id       = { type = 12700 id = 22 }
      name     = "4th Indian Division"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Calcutta Defence Force"
    location = 1285 # Dhaka
    id       = { type = 12700 id = 23 }
    division =
    { id            = { type = 12700 id = 24 }
      name          = "5th Indian Division"
      type          = infantry
      extra         = artillery
      brigade_model = 2
      strength      = 100
    }
  }
  landunit =
  { name     = "Burma Rifles"
    location = 1299 # Rangoon
    id       = { type = 12700 id = 25 }
    division =
    { id       = { type = 12700 id = 26 }
      name     = "1st (Burma) Division"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "1st North West Frontier Force"
    location = 1494 # Karachi
    id       = { type = 12700 id = 27 }
    division =
    { id       = { type = 12700 id = 28 }
      name     = "Karachi Forces"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "2nd North West Frontier Force"
    location = 1478 # Bikaner
    id       = { type = 12700 id = 29 }
    division =
    { id       = { type = 12700 id = 30 }
      name     = "Bikaner Forces"
      type     = infantry
      extra    = engineer
      strength = 100
    }
  }
  landunit =
  { name     = "Hyderabad State Troops"
    location = 1507 # Hyderabad
    id       = { type = 12700 id = 31 }
    division =
    { id       = { type = 12700 id = 32 }
      name     = "1st Hyderabad Infantry"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Baroda State Troops"
    location = 1505 # Bombay
    id       = { type = 12700 id = 33 }
    division =
    { id       = { type = 12700 id = 34 }
      name     = "Baroda Infantry"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "3rd North West Frontier Force"
    location = 1475 # Lahore
    id       = { type = 12700 id = 35 }
    division =
    { id       = { type = 12700 id = 36 }
      name     = "Lahore Forces"
      type     = infantry
      extra    = anti_tank
      strength = 100
    }
  }
  landunit =
  { name     = "Madras Defence Force"
    location = 1509 # Madras
    id       = { type = 12700 id = 37 }
    division =
    { id       = { type = 12700 id = 38 }
      name     = "Madras Forces"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Mysore State Troops"
    location = 1514 # Cochin
    id       = { type = 12700 id = 39 }
    division =
    { id       = { type = 12700 id = 40 }
      name     = "Mysore Infantry"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "Hyderabad 2nd Division"
    location = 1515 # Madurai
    id       = { type = 12700 id = 41 }
    division =
    { id       = { type = 12700 id = 42 }
      name     = "2nd Hyderabad Infantry"
      type     = infantry
      strength = 100
    }
  }
  landunit =
  { name     = "4th North West Frontier Force"
    location = 1480 # Hyderabad, Sind
    id       = { type = 12700 id = 43 }
    division =
    { id       = { type = 12700 id = 44 }
      name     = "Sind Forces"
      type     = infantry
      extra    = engineer
      strength = 100
    }
  }
  landunit =
  { name     = "Sudan Defence Force"
    location = 1066 # Khartoum
    id       = { type = 12700 id = 47 }
    division =
    { id       = { type = 12700 id = 48 }
      name     = "Sudan Defence Force"
      type     = garrison
      strength = 25 # was 45 before 1.11
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "Nigerian Local Forces"
    location = 1145 # Kano
    id       = { type = 12700 id = 49 }
    division =
    { id       = { type = 12700 id = 50 }
      name     = "Nigerian Local Forces"
      type     = militia
      strength = 50
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "Ugandan Local Forces"
    location = 1064 # Entebbe
    id       = { type = 12700 id = 51 }
    division =
    { id       = { type = 12700 id = 52 }
      name     = "Ugandan Local Forces"
      type     = militia
      strength = 50
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "KAR Northern Brigade"
    location = 1060 # Nairobi
    id       = { type = 12700 id = 53 }
    division =
    { id       = { type = 12700 id = 54 }
      name     = "1st King's African Rifles"
      type     = infantry
      strength = 25
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "WAFF Gambia"
    location = 988 # Freetown
    id       = { type = 12700 id = 45 }
    division =
    { id       = { type = 12700 id = 46 }
      name     = "1st West African Frontier Force"
      type     = infantry
      strength = 15
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "WAFF Nigeria"
    location = 1008 # Lagos
    id       = { type = 12700 id = 55 }
    division =
    { id       = { type = 12700 id = 56 }
      name     = "2nd West African Frontier Force"
      type     = infantry
      strength = 15
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "Kenyan Colonial Troops"
    location = 1060 # Nairobi
    id       = { type = 12700 id = 57 }
    division =
    { id       = { type = 12700 id = 58 }
      name     = "Kenyan Local Forces"
      type     = militia
      strength = 50
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "KAR Southern Brigade"
    location = 1061 # Mombasa
    id       = { type = 12700 id = 59 }
    division =
    { id       = { type = 12700 id = 60 }
      name     = "2nd King's African Rifles"
      type     = infantry
      extra         = artillery
      brigade_model = 0
      strength = 25
      # can_reinforce = no
    }
  }
  landunit =
  { name     = "Somaliland Camel Corps"
    location = 1035 # Berbera
    id       = { type = 12700 id = 61 }
    division =
    { id            = { type = 12700 id = 62 }
      name          = "Somaliland Camel Corps"
      type          = cavalry
      strength = 10
      # can_reinforce = no
    }
  }

  ## UK Home Garrisons ##

  landunit =
  { name     = "Plymouth Coastal Command"
    location = 23 # Plymouth
    id       = { type = 12700 id = 300 }
    division =
    { id            = { type = 12700 id = 301 }
      name          = "Plymouth Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Portsmouth Coastal Command"
    location = 21 # Portsmouth
    id       = { type = 12700 id = 302 }
    division =
    { id            = { type = 12700 id = 303 }
      name          = "Portsmouth Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Dover Coastal Command"
    location = 20 # Dover
    id       = { type = 12700 id = 304 }
    division =
    { id            = { type = 12700 id = 305 }
      name          = "Dover Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Norwich Coastal Command"
    location = 17 # Norwich
    id       = { type = 12700 id = 306 }
    division =
    { id            = { type = 12700 id = 307 }
      name          = "Norwich Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Sheffield Coastal Command"
    location = 13 # Sheffield
    id       = { type = 12700 id = 308 }
    division =
    { id            = { type = 12700 id = 309 }
      name          = "Sheffield Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Sunderland Coastal Command"
    location = 11 # Sunderland
    id       = { type = 12700 id = 310 }
    division =
    { id            = { type = 12700 id = 311 }
      name          = "Sunderland Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }  

  landunit =
  { name     = "Edinburgh Coastal Command"
    location = 10 # Edinburgh
    id       = { type = 12700 id = 312 }
    division =
    { id            = { type = 12700 id = 313 }
      name          = "Edinburgh Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Glasgow Coastal Command"
    location = 9 # Glasgow
    id       = { type = 12700 id = 314 }
    division =
    { id            = { type = 12700 id = 315 }
      name          = "Glasgow Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Dunfermline Command"
    location = 8 # Dunfermline
    id       = { type = 12700 id = 316 }
    division =
    { id            = { type = 12700 id = 317 }
      name          = "Dunfermline Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

 landunit =
  { name     = "Aberdeen Command"
    location = 7 # Aberdeen
    id       = { type = 12700 id = 318 }
    division =
    { id            = { type = 12700 id = 319 }
      name          = "Aberdeen Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Inverness Command"
    location = 6 # Inverness
    id       = { type = 12700 id = 320 }
    division =
    { id            = { type = 12700 id = 321 }
      name          = "Inverness Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Scapa Flow Command"
    location = 5 # Scapa Flow
    id       = { type = 12700 id = 322 }
    division =
    { id            = { type = 12700 id = 323 }
      name          = "Scapa Flow Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "Stornoway Command"
    location = 3 # Stornoway
    id       = { type = 12700 id = 324 }
    division =
    { id            = { type = 12700 id = 325 }
      name          = "Stornoway Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

   landunit =
  { name     = "Belfast Coastal Command"
    location = 28 # Belfast
    id       = { type = 12700 id = 326 }
    division =
    { id            = { type = 12700 id = 327 }
      name          = "Belfast Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

    landunit =
  { name     = "Portadown Coastal Command"
    location = 29 # Portadown
    id       = { type = 12700 id = 328 }
    division =
    { id            = { type = 12700 id = 329 }
      name          = "Portadown Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

     landunit =
  { name     = "Blackpool Coastal Command"
    location = 12 # Blackpool
    id       = { type = 12700 id = 330 }
    division =
    { id            = { type = 12700 id = 331 }
      name          = "Blackpool Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

      landunit =
  { name     = "Liverpool Coastal Command"
    location = 14 # Liverpool
    id       = { type = 12700 id = 332 }
    division =
    { id            = { type = 12700 id = 333 }
      name          = "Liverpool Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }


      landunit =
  { name     = "Cardiff Command"
    location = 15 # Cardiff
    id       = { type = 12700 id = 334 }
    division =
    { id            = { type = 12700 id = 335 }
      name          = "Cardiff Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

       landunit =
  { name     = "Liverpool Coastal Command"
    location = 14 # Liverpool
    id       = { type = 12700 id = 336 }
    division =
    { id            = { type = 12700 id = 337 }
      name          = "Liverpool Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

	landunit =
  { name     = "Bristol Coastal Command"
    location = 22 # Bristol
    id       = { type = 12700 id = 338 }
    division =
    { id            = { type = 12700 id = 339 }
      name          = "Bristol Coastal Forces"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }

  landunit =
  { name     = "London Command"
    location = 19 # London
    id       = { type = 12700 id = 340 }
    division =
    { id            = { type = 12700 id = 341 }
      name          = "London Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }
  
    landunit =
  { name     = "Birmingham Command"
    location = 16 # Birmingham
    id       = { type = 12700 id = 342 }
    division =
    { id            = { type = 12700 id = 343 }
      name          = "Birmingham Garrison"
      type          = garrison
      strength = 25 # was 100 before 1.11
	locked = yes
    }
  }




	### UK Navy OOB ###
  navalunit =
  { name     = "Home Fleet"
    id       = { type = 12700 id = 84 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 85 }
      name  = "HMS Nelson"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 86 }
      name  = "HMS Rodney"
      type  = battleship
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 87 }
      name  = "HMS Royal Sovereign"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 89 }
      name  = "HMS Resolution"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 90 }
      name  = "HMS Ramillies"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 149 }
      name  = "HMS Barham"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 151 }
      name  = "HMS Malaya"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 0
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 150 }
      name  = "HMS Valiant"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 230 }
      name  = "HMS Erebus, HMS Terror & HMS Marshal Soult"
      type  = battleship
      model = 0
      extra1 = none
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 91 }
      name  = "HMS Hood"
      type  = battlecruiser
      model = 2
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 0
    }
    division =
    { id    = { type = 12700 id = 92 }
      name  = "HMS Renown"
      type  = battlecruiser
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
    }
    division =
    { id    = { type = 12700 id = 94 }
      name  = "HMS Repulse"
      type  = battlecruiser
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
    }
    division =
    { id            = { type = 12700 id = 154 }
      name          = "HMS Courageous"
      type          = carrier
      model         = 1
      extra1        = cag
      brigade_model1= 2
    }
    division =
    { id            = { type = 12700 id = 93 }
      name          = "HMS Furious"
      type          = carrier
      model         = 1
      extra1        = cag
      brigade_model1= 2
    }
    division =
    { id            = { type = 12700 id = 155 }
      name          = "HMS Glorious"
      type          = carrier
      model         = 1
      extra1        = cag
      brigade_model1= 2
    }
    division =
    { id            = { type = 12700 id = 203 }
      name          = "HMS Hermes"
      type          = escort_carrier
      model 	    = 0
      extra1        = b_u1
      brigade_model1= 1
    }
    division =
    { id    = { type = 12700 id = 96 }
      name  = "HMS Cairo"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = naval_fire_controll_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 183 }
      name  = "HMS Leander"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 99 }
      name  = "HMS Neptune"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 100 }
      name  = "HMS Orion"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 222 }
      name  = "HMS Dauntless"
      type  = light_cruiser
      model = 0
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 101 }
      name  = "1st Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 102 }
      name  = "2nd Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 103 }
      name  = "3rd Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 95 }
      name  = "4th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { id       = { type = 12700 id = 104 }
    name     = "HMS Argus"
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id            = { type = 12700 id = 105 }
      name          = "HMS Argus"
      type          = escort_carrier
      model         = 0
      extra1        = b_u1
      brigade_model1= 1
    }
  }
  # 2nd Submarine Squadron#
  navalunit =
  { name     = "2nd Submarine Squadron"
    id       = { type = 12700 id = 106 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 107 }
      name  = "3rd Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 108 }
      name  = "4th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 109 }
      name  = "5th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 110 }
      name  = "6th Submarine Flotilla"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 12700 id = 111 }
      name  = "7th Submarine Flotilla"
      type  = submarine
      model = 1
    }
  }
  # 1st Transport Squadron#
  navalunit =
  { name     = "1st Transport Squadron"
    id       = { type = 12700 id = 112 }
    location = 1505 # Hyderabad
    base     = 1505
    division =
    { id    = { type = 12700 id = 113 }
      name  = "Suffolk Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 114 }
      name  = "Trojan Star Flotilla"
      type  = transport
      model = 0
    }
  }
  # 2nd Transport Squadron#
  navalunit =
  { name     = "2nd Transport Squadron"
    id       = { type = 12700 id = 115 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 116 }
      name  = "Empire Arquebus Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 117 }
      name  = "Hororata Flotilla"
      type  = transport
      model = 0
    }
  }
  # 3rd Transport Squadron#
  navalunit =
  { name     = "3rd Transport Squadron"
    id       = { type = 12700 id = 118 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 119 }
      name  = "Clan Macauley Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 120 }
      name  = "Empire Captain Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 121 }
      name  = "Andes Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 122 }
      name  = "Empire Charmain Flotilla"
      type  = transport
      model = 0
    }
  }
  # 4th Transport Squadron#
  navalunit =
  { name     = "4th Transport Squadron"
    id       = { type = 12700 id = 123 }
    location = 5 # Scapa Flow
    base     = 5
    division =
    { id    = { type = 12700 id = 124 }
      name  = "Essex Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 125 }
      name  = "Maloja Flotilla"
      type  = transport
      model = 0
    }
  }
  # 5th Transport Squadron#
  navalunit =
  { name     = "5th Transport Squadron"
    id       = { type = 12700 id = 126 }
    location = 23 # Plymouth
    base     = 23
    division =
    { id    = { type = 12700 id = 127 }
      name  = "Empire Splendour Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 128 }
      name  = "Sam Torch Flotilla"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 12700 id = 129 }
      name  = "Resolution Flotilla"
      type  = transport
      model = 0
    }
  }
  # Non-Associated Destroyers#
  navalunit =
  { name     = "1st Destroyer Squadron"
    id       = { type = 12700 id = 130 }
    location = 23 # Plymouth
    base     = 23
    division =
    { id    = { type = 12700 id = 131 }
      name  = "5th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 132 }
      name  = "6th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 133 }
      name  = "7th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "2nd Destroyer Squadron"
    id       = { type = 12700 id = 134 }
    location = 14
    base     = 14
    division =
    { id    = { type = 12700 id = 135 }
      name  = "8nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 136 }
      name  = "9th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "3rd Destroyer Squadron"
    id       = { type = 12700 id = 137 }
    location = 14 # Actually based at Milford Haven, but that is located in the same province as Cardiff.
    base     = 14
    division =
    { id    = { type = 12700 id = 138 }
      name  = "10th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 139 }
      name  = "11th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "4th Destroyer Squadron"
    id       = { type = 12700 id = 140 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 141 }
      name  = "12th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 142 }
      name  = "13th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "5th Destroyer Squadron"
    id       = { type = 12700 id = 143 }
    location = 21 # Portsmouth
    base     = 21
    division =
    { id    = { type = 12700 id = 144 }
      name  = "14th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 145 }
      name  = "15th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 146 }
      name  = "16th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  navalunit =
  { name     = "Mediterranean Fleet"
    id       = { type = 12700 id = 147 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 12700 id = 148 }
      name  = "HMS Queen Elizabeth"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = none
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 0
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 153 }
      name  = "HMS Revenge"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 156 }
      name  = "HMS Devonshire"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 157 }
      name  = "HMS London"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 158 }
      name  = "HMS Shropshire"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 159 }
      name  = "HMS Sussex"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 160 }
      name  = "HMS Exeter"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 161 }
      name  = "HMS York"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 97 }
      name  = "HMS Galatea"
      type  = light_cruiser
      model = 2
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 167 }
      name  = "HMS Arethusa"
      type  = light_cruiser
      model = 2
      extra1 = naval_spotter_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 98 }
      name  = "HMS Dunedin"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 163 }
      name  = "HMS Curlew"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 164 }
      name  = "HMS Delhi"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 165 }
      name  = "HMS Despatch"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 166 }
      name  = "HMS Durban"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 168 }
      name  = "17th Destroyer Flotilla"
      type  = destroyer
      model = 1
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 169 }
      name  = "18th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 170 }
      name  = "19th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 171 }
      name  = "20th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 172 }
      name  = "21st Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 12700 id = 173 }
      name  = "22nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
  }
  # 1st Submarine Squadron#
  navalunit =
  { name     = "1st Submarine Squadron"
    id       = { type = 12700 id = 174 }
    location = 906 # Alexandria
    base     = 906
    division =
    { id    = { type = 12700 id = 175 }
      name  = "1st Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 12700 id = 176 }
      name  = "2nd Submarine Flotilla"
      type  = submarine
      model = 7
    }
  }
  # America & West Indies Station#
  navalunit =
  { name     = "America & West Indies Station"
    id       = { type = 12700 id = 177 }
    location = 538 # Bermuda
    base     = 538
    division =
    { id    = { type = 12700 id = 178 }
      name  = "HMS Dragon"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 179 }
      name  = "HMS Ajax"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 180 }
      name  = "23rd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 181 }
      name  = "24th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  # Africa Station#
  navalunit =
  { name     = "Africa Station"
    id       = { type = 12700 id = 182 }
    location = 988 # Freetown
    base     = 988
    division =
    { id    = { type = 12700 id = 206 }
      name  = "HMS Dorsetshire"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 184 }
      name  = "HMS Carlisle"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 185 }
      name  = "25th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_anti_air_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 186 }
      name  = "26th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  # East Indies Station#
  navalunit =
  { name     = "East Indies Station"
    id       = { type = 12700 id = 187 }
    location = 1517
    base     = 1517
    division =
    { id    = { type = 12700 id = 188 }
      name  = "HMS Norfolk"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 2
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 189 }
      name  = "HMS Diomede"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 190 }
      name  = "HMS Emerald"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 191 }
      name  = "HMS Enterprise"
      type  = light_cruiser
      model = 1
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 0
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 192 }
      name  = "27th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
    division =
    { id    = { type = 12700 id = 193 }
      name  = "28th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  }
  # China Station#
  navalunit =
  { name     = "China Station"
    id       = { type = 12700 id = 194 }
    location = 1315 # Hong Kong
    base     = 1315
    division =
    { id            = { type = 12700 id = 195 }
      name          = "HMS Eagle"
      type          = escort_carrier
      model         = 1
      extra1        = b_u1
      brigade_model1= 1
    }
    division =
    { id    = { type = 12700 id = 208 }
      name  = "HMS Berwick"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 209 }
      name  = "HMS Cornwall"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 211 }
      name  = "HMS Suffolk"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 212 }
      name  = "HMS Kent"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
    }
    division =
    { id    = { type = 12700 id = 196 }
      name  = "HMS Capetown"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 1
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 221 }
      name  = "HMS Danae"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 1
      brigade_model2 = 1
    }
    division =
    { id    = { type = 12700 id = 197 }
      name  = "29th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 12700 id = 198 }
      name  = "30th Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 1
    }
  }
  # 3rd Submarine Squadron#
  navalunit =
  { name     = "3rd Submarine Squadron"
    id       = { type = 12700 id = 199 }
    location = 1315 # Hong Kong
    base     = 1315
    division =
    { id    = { type = 12700 id = 200 }
      name  = "8th Submarine Flotilla"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 12700 id = 201 }
      name  = "9th Submarine Flotilla"
      type  = submarine
      model = 2
    }
  }
  # Reserve Fleet#
  navalunit =
  { name     = "Reserve Fleet"
    id       = { type = 12700 id = 202 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 204 }
      name  = "HMS Effingham"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 205 }
      name  = "HMS Frobisher"
      type  = heavy_cruiser
      model = 0
      extra1 = none
      extra2 = none
      extra3 = none
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 207 }
      name  = "HMS Hawkins"
      type  = heavy_cruiser
      model = 0
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_anti_air_l
      brigade_model1 = 0
      brigade_model2 = 0
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 213 }
      name  = "HMS Caledon"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 214 }
      name  = "HMS Calypso"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 215 }
      name  = "HMS Caradoc"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 216 }
      name  = "HMS Calcutta"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 217 }
      name  = "HMS Colombo"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 218 }
      name  = "HMS Cardiff"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 219 }
      name  = "HMS Ceres"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 220 }
      name  = "HMS Curacoa"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 231 }
      name  = "HMS Castor"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 232 }
      name  = "HMS Constance"
      type  = light_cruiser
      model = 0
      extra1 = naval_fire_controll_s
      extra2 = naval_anti_air_s
      brigade_model1 = 0
      brigade_model2 = 0
    }
    division =
    { id    = { type = 12700 id = 224 }
      name  = "31st Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
    division =
    { id    = { type = 12700 id = 225 }
      name  = "32nd Destroyer Flotilla"
      type  = destroyer
      model = 0
      extra1 = naval_fire_controll_s
      brigade_model1 = 0
    }
  }
  # Shipyards #
  navalunit =
  { name     = "Devonport Shipyard"
    id       = { type = 12700 id = 229 }
    location = 21 # Southampton
    base     = 21
    division =
    { id    = { type = 12700 id = 88 }
      name  = "HMS Royal Oak"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 2
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 152 }
      name  = "HMS Warspite"
      type  = battleship
      model = 1
      extra1 = naval_sa_l
      extra2 = naval_fire_controll_l
      extra3 = naval_spotter_l
      extra4 = naval_anti_air_l
      extra5 = none
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 1
      brigade_model4 = 1
      brigade_model5 = 0
    }
    division =
    { id    = { type = 12700 id = 210 }
      name  = "HMS Cumberland"
      type  = heavy_cruiser
      model = 1
      extra1 = naval_fire_controll_l
      extra2 = naval_spotter_l
      extra3 = naval_anti_air_l
      brigade_model1 = 1
      brigade_model2 = 1
      brigade_model3 = 0
    }
    division =
    { id    = { type = 12700 id = 223 }
      name  = "HMS Achilles"
      type  = light_cruiser
      model = 2
      extra1 = naval_fire_controll_s
      extra2 = naval_spotter_s
      brigade_model1 = 1
      brigade_model2 = 2
    }
    division =
    { id    = { type = 12700 id = 162 }
      name  = "HMS Coventry"
      type  = light_cruiser
      model = 0
      extra1 = none
      extra2 = none
      brigade_model1 = 0
      brigade_model2 = 0
    }
  }
  # #################
  #  Royal Airforce #
  # #################
  airunit =
  { location = 14
    base     = 14
    id       = { type = 12700 id = 67 }
    name     = "1st Tactical Wing"
    division =
    { id       = { type = 12700 id = 64 }
      name     = "No.1 RAF Tactical Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 17
    base     = 17
    id       = { type = 12700 id = 65 }
    name     = "RAF Strategic Bomber Command"
    division =
    { id       = { type = 12700 id = 66 }
      name     = "No.2 RAF Strategic Group"
      type     = strategic_bomber
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 12700 id = 68 }
      name     = "no.3 RAF Strategic Group"
      type     = strategic_bomber
      model    = 0
      strength = 100
    }
    division =
    { id       = { type = 12700 id = 69 }
      name     = "no.4 RAF Strategic Group"
      type     = strategic_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 12700 id = 70 }
    name     = "2nd Tactical Wing"
    division =
    { id       = { type = 12700 id = 71 }
      name     = "No.5 RAF Tactical Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 14
    base     = 14
    id       = { type = 12700 id = 72 }
    name     = "1st Fighter Wing"
    division =
    { id       = { type = 12700 id = 73 }
      name     = "No.11 RAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 12700 id = 74 }
    name     = "2nd Fighter Wing"
    division =
    { id       = { type = 12700 id = 75 }
      name     = "No.12 RAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 21
    base     = 21
    id       = { type = 12700 id = 76 }
    name     = "3rd Fighter Wing"
    division =
    { id       = { type = 12700 id = 77 }
      name     = "No.13 RAF Fighter Group"
      type     = interceptor
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 1798
    base     = 1798
    id       = { type = 12700 id = 78 }
    name     = "Middle East Air Command"
    division =
    { id       = { type = 12700 id = 79 }
      name     = "Middle East Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 1505
    base     = 1505
    id       = { type = 12700 id = 80 }
    name     = "India Air Command"
    division =
    { id       = { type = 12700 id = 81 }
      name     = "Indian Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
    }
  }
  airunit =
  { location = 1353
    base     = 1353
    id       = { type = 12700 id = 82 }
    name     = "Far East Air Command"
    division =
    { id       = { type = 12700 id = 83 }
      name     = "Far East Group"
      type     = tactical_bomber
      model    = 0
      strength = 100
    }
  }
  # Warships Under Construction#
	convoy = { 
		id = { type = 12700 id = 242 } 
		istradeconvoy = no 
		transports = 25 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 444 2463 2448 2443 2441 2439 2438 2435 2433 2432 2431 2430 2429 2428 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 243 } 
		istradeconvoy = no 
		transports = 35 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 1517 2047 2048 2049 2050 2026 2022 2013 2010 2007 2272 2582 2287 2288 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 244 } 
		istradeconvoy = no 
		transports = 35 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = yes 
		supplies = no 
		path = { 1820 2041 2040 2039 2038 2037 2035 2034 2027 2022 2013 2010 2007 2272 2582 2287 2288 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 245 } 
		istradeconvoy = no 
		transports = 35 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = yes 
		supplies = no 
		path = { 1822 2041 2040 2039 2038 2037 2035 2034 2027 2022 2013 2010 2007 2272 2582 2287 2288 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 246 } 
		istradeconvoy = no 
		transports = 25 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 901 2454 2451 2442 2440 2437 2435 2433 2432 2431 2430 2429 2428 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 247 } 
		istradeconvoy = no 
		transports = 45 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 1353 2146 2144 2077 2076 2071 2070 2064 2065 2014 2009 2007 2272 2582 2287 2288 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 248 } 
		istradeconvoy = no 
		transports = 30 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = yes 
		supplies = no 
		path = { 1644 2145 2144 2077 2076 2071 2070 2064 2065 2014 2009 2007 2272 2582 2287 2288 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 249 } 
		istradeconvoy = no 
		transports = 20 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 873 2517 2542 2543 2308 2306 2304 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 250 } 
		istradeconvoy = no 
		transports = 15 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = yes 
		supplies = no 
		path = { 809 2518 2577 2543 2308 2306 2304 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 251 } 
		istradeconvoy = no 
		transports = 20 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 1002 2290 2291 2292 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 252 } 
		istradeconvoy = no 
		transports = 20 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 1008 2289 2581 2288 2580 2295 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 253 } 
		istradeconvoy = no 
		transports = 15 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 988 2293 2294 2296 2594 2300 2593 2424 2595 2420 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 254 } 
		istradeconvoy = no 
		transports = 15 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 576 2340 2354 2360 2359 2422 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 255 } 
		istradeconvoy = no 
		transports = 30 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = no 
		supplies = no 
		path = { 1611 2180 1951 1975 1974 1986 1987 1968 1963 2574 2575 2576 2524 2539 2540 2314 2312 2353 2355 2360 2359 2422 2597 2411 23 } 
		} 
	convoy = { 
		id = { type = 12700 id = 290 } 
		trade_id = { type = 16384 id = 345 } 
		istradeconvoy = yes 
		transports = 38 
		escorts = 0 
		rare_materials = yes 
		energy = yes 
		metal = yes 
		oil = yes 
		supplies = no 
		path = { 23 2411 2597 2422 2359 2360 2354 2352 2347 2348 606 } 
		} 
	province_development = { 
		id = { type = 12700 id = 256 } 
		name = "" 
		progress = 0.0000 
		location = 19 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 257 } 
		name = "" 
		progress = 0.0000 
		location = 14 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 258 } 
		name = "" 
		progress = 0.0000 
		location = 16 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 259 } 
		name = "" 
		progress = 0.0000 
		location = 13 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 260 } 
		name = "" 
		progress = 0.0000 
		location = 11 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 261 } 
		name = "" 
		progress = 0.0000 
		location = 12 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 262 } 
		name = "" 
		progress = 0.0000 
		location = 9 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 263 } 
		name = "" 
		progress = 0.0000 
		location = 15 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 264 } 
		name = "" 
		progress = 0.0000 
		location = 17 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 265 } 
		name = "" 
		progress = 0.0000 
		location = 20 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 266 } 
		name = "" 
		progress = 0.0000 
		location = 1471 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 267 } 
		name = "" 
		progress = 0.0000 
		location = 21 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 268 } 
		name = "" 
		progress = 0.0000 
		location = 22 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 269 } 
		name = "" 
		progress = 0.0000 
		location = 28 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 270 } 
		name = "" 
		progress = 0.0000 
		location = 1517 
		cost = 2.0000 
		date = { 
			year = 1949 
			month = august 
			day = 20 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 271 } 
		name = "" 
		progress = 0.0000 
		location = 1353 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = may 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 272 } 
		name = "" 
		progress = 0.0000 
		location = 1352 
		cost = 2.0000 
		date = { 
			year = 1951 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 273 } 
		name = "" 
		progress = 0.0000 
		location = 1349 
		cost = 2.0000 
		date = { 
			year = 1951 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 274 } 
		name = "" 
		progress = 0.0000 
		location = 1350 
		cost = 2.0000 
		date = { 
			year = 1951 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 275 } 
		name = "" 
		progress = 0.0000 
		location = 1351 
		cost = 2.0000 
		date = { 
			year = 1951 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 276 } 
		name = "" 
		progress = 0.0000 
		location = 1514 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 277 } 
		name = "" 
		progress = 0.0000 
		location = 1459 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 278 } 
		name = "" 
		progress = 0.0000 
		location = 1285 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 279 } 
		name = "" 
		progress = 0.0000 
		location = 1507 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 280 } 
		name = "" 
		progress = 0.0000 
		location = 23 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = july 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 281 } 
		name = "" 
		progress = 0.0000 
		location = 10 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1725 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 282 } 
		name = "" 
		progress = 0.0000 
		location = 19 
		cost = 5.0000 
		date = { 
			year = 1944 
			month = november 
			day = 23 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 4752 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 12700 id = 283 } 
		name = "" 
		progress = 0.0000 
		location = 14 
		cost = 5.0000 
		date = { 
			year = 1944 
			month = november 
			day = 23 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 4752 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 12700 id = 284 } 
		name = "" 
		progress = 0.0000 
		location = 16 
		cost = 5.0000 
		date = { 
			year = 1944 
			month = november 
			day = 23 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 4752 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 12700 id = 285 } 
		name = "" 
		progress = 0.0000 
		location = 13 
		cost = 5.0000 
		date = { 
			year = 1944 
			month = may 
			day = 20 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3168 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 12700 id = 286 } 
		name = "" 
		progress = 0.0000 
		location = 11 
		cost = 5.0000 
		date = { 
			year = 1944 
			month = may 
			day = 20 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3168 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 12700 id = 287 } 
		name = "" 
		progress = 0.0000 
		location = 12 
		cost = 5.0000 
		date = { 
			year = 1944 
			month = may 
			day = 20 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 10 
		done = 0 
		days = 3168 
		days_for_first = 302 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 12700 id = 288 } 
		name = "" 
		progress = 0.0000 
		location = 1457 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 289 } 
		name = "" 
		progress = 0.0000 
		location = 1511 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1000 } 
		name = "" 
		progress = 0.0000 
		location = 7 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1001 } 
		name = "" 
		progress = 0.0000 
		location = 8 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1002 } 
		name = "" 
		progress = 0.0000 
		location = 1477 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1003 } 
		name = "" 
		progress = 0.0000 
		location = 1472 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1004 } 
		name = "" 
		progress = 0.0000 
		location = 1468 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 18 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 101 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1005 } 
		name = "" 
		progress = 0.0000 
		location = 1505 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1006 } 
		name = "" 
		progress = 0.0000 
		location = 1466 
		cost = 2.0000 
		date = { 
			year = 1946 
			month = december 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 202 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1007 } 
		name = "" 
		progress = 0.0000 
		location = 576 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = june 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1008 } 
		name = "" 
		progress = 0.0000 
		location = 1129 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = january 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2724 
		days_for_first = 126 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1009 } 
		name = "" 
		progress = 0.0000 
		location = 1009 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = january 
			day = 10 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2724 
		days_for_first = 126 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1010 } 
		name = "" 
		progress = 0.0000 
		location = 1460 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1011 } 
		name = "" 
		progress = 0.0000 
		location = 1461 
		cost = 2.0000 
		date = { 
			year = 1944 
			month = march 
			day = 2 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 2058 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1012 } 
		name = "" 
		progress = 0.0000 
		location = 1304 
		cost = 2.0000 
		date = { 
			year = 1956 
			month = april 
			day = 6 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 36 
		done = 0 
		days = 3057 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1013 } 
		name = "" 
		progress = 0.0000 
		location = 1346 
		cost = 2.0000 
		date = { 
			year = 1951 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1014 } 
		name = "" 
		progress = 0.0000 
		location = 871 
		cost = 2.0000 
		date = { 
			year = 1951 
			month = november 
			day = 5 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1015 } 
		name = "" 
		progress = 0.0000 
		location = 873 
		cost = 2.0000 
		date = { 
			year = 1945 
			month = june 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 2391 
		days_for_first = 151 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 12700 id = 1016 } 
		name = "" 
		progress = 0.0000 
		location = 1644 
		cost = 2.0000 
		date = { 
			year = 1954 
			month = january 
			day = 20 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 32 
		done = 0 
		days = 2724 
		days_for_first = 252 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	convoy_development = { 
		id = { type = 12700 id = 1017 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1938 
			month = august 
			day = 11 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 1 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 12700 id = 1018 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1938 
			month = august 
			day = 11 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 1 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 12700 id = 1019 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1938 
			month = august 
			day = 11 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 1 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 12700 id = 1020 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1938 
			month = august 
			day = 11 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 1 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 12700 id = 1021 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 2.0000 
		date = { 
			year = 1938 
			month = august 
			day = 11 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 1 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = escorts 
		} 
	convoy_development = { 
		id = { type = 12700 id = 1022 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 2.0000 
		date = { 
			year = 1938 
			month = august 
			day = 11 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 15 
		done = 0 
		days = 1 
		days_for_first = 76 
		gearing_bonus = 0.0000 
		type = escorts 
		} 
#	division_development = { 
#		id = { type = 12700 id = 240 } 
#		name = "HMS Glasgow" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.3554 
#		date = { 
#			year = 1936 
#			month = april 
#			day = 26 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.2955 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 166 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_fire_controll_s 
#		extra2 = naval_spotter_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 1 
#		brigade_model2 = 2 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
#	division_development = { 
#		id = { type = 12700 id = 241 } 
#		name = "HMS Sheffield" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.3554 
#		date = { 
#			year = 1936 
#			month = april 
#			day = 16 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.3571 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 166 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_fire_controll_s 
#		extra2 = naval_spotter_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 1 
#		brigade_model2 = 2 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
#	division_development = { 
#		id = { type = 12700 id = 239 } 
#		name = "HMS Birmingham" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.3554 
#		date = { 
#			year = 1936 
#			month = may 
#			day = 13 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.1940 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 166 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_fire_controll_s 
#		extra2 = naval_spotter_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 1 
#		brigade_model2 = 2 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
	division_development = { 
		id = { type = 12700 id = 238 } 
		name = "HMS Southampton" 
		progress = 0.0000 
		location = 0 
		cost = 4.1383 
		date = { 
			year = 1936 
			month = october 
			day = 28 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9743 # 0.4848
		size = 3 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = naval_spotter_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 237 } 
		name = "HMS Newcastle" 
		progress = 0.0000 
		location = 0 
		cost = 4.1383 
		date = { 
			year = 1936 
			month = june 
			day = 21 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8703 # 0.5132
		size = 2 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = naval_spotter_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 236 } 
		name = "HMS Aurora" 
		progress = 0.0000 
		location = 0 
		cost = 3.4301 
		date = { 
			year = 1936 
			month = may 
			day = 7 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.1964 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 227 } 
		name = "34th Destroyer Flotilla" 
		progress = 0.0000 
		location = 0 
		cost = 3.2304 
		date = { 
			year = 1936 
			month = march 
			day = 26 
			hour = 0 
			} 
		manpower = 0.7000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0808 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 94 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 226 } 
		name = "33rd Destroyer Flotilla" 
		progress = 0.0000 
		location = 0 
		cost = 3.2304 
		date = { 
			year = 1936 
			month = february 
			day = 27 
			hour = 0 
			} 
		manpower = 0.7000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.3838 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 94 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = naval_fire_controll_s 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 228 } 
		name = "10th Submarine Flotilla" 
		progress = 0.0000 
		location = 0 
		cost = 1.5120 
		date = { 
			year = 1936 
			month = february 
			day = 28 
			hour = 0 
			} 
		manpower = 0.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.5197 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 121 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 233 } 
		name = "HMS Penelope" 
		progress = 0.0000 
		location = 0 
		cost = 3.4478 
		date = { 
			year = 1936 
			month = february 
			day = 26 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.6467 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 234 } 
		name = "HMS Amphion" # HMAS Perth since 1939
		progress = 0.0000 
		location = 0 
		cost = 3.3324 
		date = { 
			year = 1936 
			month = january 
			day = 24 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8450 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 12700 id = 235 } 
		name = "HMS Apollo" 
		progress = 0.0000 
		location = 0 
		cost = 3.3324 
		date = { 
			year = 1936 
			month = january 
			day = 2 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.9862 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 159 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	province_development = { 
		id = { type = 12700 id = 1023 } 
		name = "" 
		progress = 0.0000 
		location = 906 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = september 
			day = 3 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 2138 
		days_for_first = 454 
		gearing_bonus = 0.0000 
		type = land_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1024 } 
		name = "" 
		progress = 0.0000 
		location = 21 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1025 } 
		name = "" 
		progress = 0.0000 
		location = 23 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1026 } 
		name = "" 
		progress = 0.0000 
		location = 17 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1027 } 
		name = "" 
		progress = 0.0000 
		location = 13 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1028 } 
		name = "" 
		progress = 0.0000 
		location = 22 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1029 } 
		name = "" 
		progress = 0.0000 
		location = 11 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1030 } 
		name = "" 
		progress = 0.0000 
		location = 10 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1031 } 
		name = "" 
		progress = 0.0000 
		location = 9 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1032 } 
		name = "" 
		progress = 0.0000 
		location = 12 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1033 } 
		name = "" 
		progress = 0.0000 
		location = 14 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1034 } 
		name = "" 
		progress = 0.0000 
		location = 28 
		cost = 4.0000 
		date = { 
			year = 1939 
			month = april 
			day = 27 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 3 
		done = 0 
		days = 1254 
		days_for_first = 420 
		gearing_bonus = 0.0000 
		type = coastal_fort 
		} 
	province_development = { 
		id = { type = 12700 id = 1035 } 
		name = "" 
		progress = 0.0000 
		location = 19 
		cost = 5.0000 
		date = { 
			year = 1941 
			month = september 
			day = 3 
			hour = 0 
			} 
		manpower = 0.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 5 
		done = 0 
		days = 2138 
		days_for_first = 454 
		gearing_bonus = 0.0000 
		type = land_fort 
		}
}
