
##############################
# Country definition for USA #
##############################

province =
{ id         = 549
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Anchorage
province = { id = 553 supplypool = 10 } # Juneau # was 1000 supplies before 1.11
province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id         = 600
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Boston
province =
{ id         = 602
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # New York
province =
{ id         = 606
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Washington D.C.
province = { id = 608 anti_air = 2 } # Philadelphia
province =
{ id       = 614
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province =
{ id       = 616
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Detroit
province =
{ id       = 620
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Chicago
province =
{ id       = 621
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Milwaukee
province =
{ id         = 633
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Norfolk
province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id       = 644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charleston
province =
{ id       = 648
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Jacksonville
province =
{ id         = 651
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Miami
province = { id = 662 supplypool = 10 } # Midway Island # was 100 supplies before 1.11
province =
{ id         = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 10 # was 1000 supplies before 1.11
}              # Pearl Harbour
province =
{ id       = 670
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Memphis
province =
{ id       = 678
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Biloxi
province =
{ id       = 684
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Little Rock
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 692
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Des Moines
province =
{ id       = 693
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province =
{ id       = 707
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Denver
province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Houston
province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 730
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
province =
{ id         = 748
  anti_air   = 1
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 8 current_size = 8 }
}              # Corpus Christi
province =
{ id         = 761
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # San Diego
province =
{ id         = 762
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Los Angeles
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 765
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # San Francisco
province =
{ id         = 780
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Seattle
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province =
{ id         = 889
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 35 # was 100 supplies before 1.11
}              # Colon
province = { id = 895 supplypool = 5 } # Puerto Rico # was 50 supplies before 1.11
province = { id = 1408 supplypool = 5 } # Attu Island # was 500 supplies before 1.11
province =
{ id         = 1624
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 10 # was 100 supplies before 1.11
}              # Guam
province = { id = 1756 supplypool = 5 } # Samoa # was 50 supplies before 1.11
province = { id = 1762 supplypool = 1 } # Phoenix Island
province = { id = 1765 supplypool = 5 } # Palmyra # was 50 supplies before 1.11
province = { id = 1766 supplypool = 1 } # Johnson Island
province =
{ id         = 1786
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 10 # was 100 supplies before 1.11
}              # Wake Island

#####################
# Country main data #
#####################

country =
{ tag                    = USA
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 2995
  money                  = 100
  consumer = 0.1650 
  supply = 0.0877 
  production = 0.7473 
  reinforcement = 0.0000 
  upgrading = 0.0000 
  manpower               = 65.4 # 100 + 7.5 from Phillippine Division - building queue
  transports             = 240
  escorts                = 53
  peacetime_ic_mod       = 0.50
  capital                = 606
  diplomacy =
  { relation =
    { tag        = ARG
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = AST value = 125 }
    relation = { tag = AFG value = -12 }
	relation = { tag = BEL value = 75 }
    relation = { tag = BHU value = 100 }
    relation =
    { tag        = BOL
      value      = 85
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = BRA
      value      = 120
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = CAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = CHL
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = COL
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = COS
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = CUB
      value      = 200
      guaranteed = { day = 30 month = december year = 1935 }
      access     = yes
    }
    relation = { tag = DEN value = 75 }
    relation =
    { tag        = DOM
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = ECU
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = 90 }
    relation = { tag = FRA value = 65 }
    relation = { tag = GER value = -10 }
    relation =
    { tag        = GUA
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = HAI
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = HOL value = 70 }
    relation =
    { tag        = HON
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = IRQ value = 120 }
    relation = { tag = JAP value = 15 }
    relation = { tag = LIB value = 200 access = yes }
    relation = { tag = MAN value = 1 }
    relation =
    { tag        = MEX
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = NEP value = 100 }
    relation =
    { tag        = NIC
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = NOR value = 75 }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation =
    { tag        = PAN
      value      = 175
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = PAR
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation =
    { tag        = PRU
      value      = 75
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = SAF value = 125 }
    relation =
    { tag        = SAL
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = SOV value = 35 }
    relation = { tag = SCH value = 1 }
    relation = { tag = SWE value = 75 }
    relation =
    { tag        = URU
      value      = 100
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation =
    { tag        = VEN
      value      = 125
      guaranteed = { day = 30 month = december year = 1935 }
    }
    relation = { tag = YEM value = 100 }
	relation = { tag = SIA value = -7 }
	relation = { tag = POR value = -2 }
	relation = { tag = ROM value = 2 }
	relation = { tag = POL value = 2 }
  }
  SpyInfo                = { country = "USA" NumberOfSpies = 5 }
  SpyInfo                = { country = "ENG" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 1 }
  SpyInfo                = { country = "AST" NumberOfSpies = 1 }
  SpyInfo                = { country = "VEN" NumberOfSpies = 3 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 3 }
  SpyInfo                = { country = "POL" NumberOfSpies = 1 }
  SpyInfo                = { country = "PAN" NumberOfSpies = 5 }
  SpyInfo                = { country = "ECU" NumberOfSpies = 1 }
  SpyInfo                = { country = "BOL" NumberOfSpies = 2 }
  SpyInfo                = { country = "CAN" NumberOfSpies = 3 }
  SpyInfo                = { country = "CUB" NumberOfSpies = 4 }
  SpyInfo                = { country = "SCH" NumberOfSpies = 2 }
  SpyInfo                = { country = "DOM" NumberOfSpies = 3 }
  SpyInfo                = { country = "GUA" NumberOfSpies = 2 }
  SpyInfo                = { country = "HAI" NumberOfSpies = 2 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "NIC" NumberOfSpies = 1 }
  SpyInfo                = { country = "SAL" NumberOfSpies = 1 }
  SpyInfo                = { country = "PRU" NumberOfSpies = 1 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 1 }
  SpyInfo                = { country = "PHI" NumberOfSpies = 3 }
  SpyInfo                = { country = "CHL" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 1 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 1 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 4 }
  nationalprovinces      = { 542 543 544 545 546 547 548 549 550 551 553 582 583 592 593 594 595 596 597 598 599 
							 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619 620 
							 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 
							 642 643 644 645 646 647 648 649 650 651 669 670 671 672 673 674 675 676 677 678 679 
							 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 
							 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 
							 722 723 724 725 726 727 728 729 730 731 732 733 734 736 735 746 748 761 762 763 764 
							 765 766 768 769 767 770 771 772 773 774 775 776 777 778 779 780 781 782 783 784 785 
							 786 787 788 789 790 791 792 793 895 889 1408 
                           }
  ownedprovinces         = { 542 543 544 545 546 547 548 549 550 551 553 582 583 592 593 594 595 596 597 598 599
							 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 617 616 618 619 620
							 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641
							 642 643 644 645 646 647 648 649 650 651 658 659 660 661 662 663 669 670 671 672 673
							 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694
							 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715
							 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736
                             746 748 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 778 779
							 780 781 782 783 784 785 786 787 788 789 790 791 792 793 895 889
							 1408 1624 1756 1762 1764 1765 1766 1786
                           }
  controlledprovinces    = { 542 543 544 545 546 547 548 549 550 551 553 582 583 592 593 594 595 596 597 598 599
							 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 617 616 618 619 620
							 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641
							 642 643 644 645 646 647 648 649 650 651 658 659 660 661 662 663 669 670 671 672 673
							 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694
							 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715
							 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736
                             746 748 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 778 779
							 780 781 782 783 784 785 786 787 788 789 790 791 792 793 895 889
							 1408 1624 1756 1762 1764 1765 1766 1786
                           }
  # early esc car
  # USA 1936 techs
  # ######################
  techapps               = { 12100 4010 4020 4120 4130 4250 4260 4190 4220 2150 2010 2290 2300 2310 2450 2460 2510 1010 1190 1200 
                             1310 5010 5020 5050 5060 5080 5090 5310 5320 5470 5480 9010 9020 9030 9140 6010 6020 8010 8020 8030 
                             8040 8050 8060 8090 8100 3010 3020 3070 3080 3130 3140 3150 3190 3200 3210 3250 3260 3270 3280 3320 
                             3330 3340 3400 3410 3420 14000 3470 5290 3100 3160 3090 5190
                           }
  blueprints             = { 1150 }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    free_market       = 10
    professional_army = 1
    defense_lobby     = 1
    interventionism   = 1
  }
  headofstate            = { type = 9 id = 6001 }
  headofgovernment       = { type = 9 id = 6002 }
  foreignminister        = { type = 9 id = 6003 }
  armamentminister       = { type = 9 id = 6004 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6006 }
  chiefofstaff           = { type = 9 id = 6007 }
  chiefofarmy            = { type = 9 id = 6008 }
  chiefofnavy            = { type = 9 id = 6158 }
  chiefofair             = { type = 9 id = 6010 }

  nationalidentity = "policy_identity_guardians" 
	socialpolicy = "policy_social_enterprise" 
	nationalculture = "policy_culture_enterprise"

 #####################################
	### USA land OOB ###
 #####################################
  landunit =
  { id       = { type = 14800 id = 1 }
    name     = "Panama Canal Force"
    location = 889
    division =
    { id     = { type = 14800 id = 2 }
      name   = "Panama Canal Garrison"
      type   = garrison
      model  = 0
      locked = yes
      extra  = artillery
    }
  }
  landunit =
  { location = 603
    name     = "1st US Army Corps"
    id       = { type = 14800 id = 3 }
    division =
    { id   = { type = 14800 id = 4 }
      name = "1st 'Big Red One' Division"
      type = infantry
    }
  }
  landunit =
  { location = 606
    name     = "2nd US Army Corps"
    id       = { type = 14800 id = 5 }
    division =
    { id   = { type = 14800 id = 6 }
      name = "2nd 'Indianhead' Division"
      type = infantry
    }
  }
  landunit =
  { location = 762
    name     = "3rd US Army Corps"
    id       = { type = 14800 id = 7 }
    division =
    { id   = { type = 14800 id = 8 }
      name = "3rd 'Rock of the Marne' Division"
      type = infantry
    }
  }
  landunit =
  { location = 707
    name     = "United States Cavalry"
    id       = { type = 14800 id = 9 }
    division =
    { id   = { type = 14800 id = 10 }
      name = "1st Cavalry 'The 1st Team' Div."
      type = cavalry
    }
  }
  landunit =
  { location = 1737
    name     = "Phillippine Force"
    id       = { type = 14800 id = 11 }
    division =
    { id     = { type = 14800 id = 12 }
      name   = "Phillippine Division"
      type   = infantry
      strength = 25 # was 100 before 1.11
      locked = yes
    }
  }
 ########################################
	### USA Navy OOB ###
 ########################################
  # US PACIFIC FLEET-SAN DIEGO, CALIFORNIA
  # Battleship Division 1
  # Nevada, Arizona, Pennsylvania
  navalunit =
  { name     = "USN Battleship Fleet 1"
    id       = { type = 14800 id = 26 }
    location = 761
    base     = 761
    division =
    { id            = { type = 14800 id = 27 }
      name          = "USS Lexington"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 14800 id = 28 }
      name  = "USS Nevada"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
division =     
{ id    = { type = 14800 id = 170 }
      name  = "USS Pennsylvania"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 29 }
      name  = "USS Arizona"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
  }
  # Battleship Division 2
  # Oklahoma, Tennessee, California
  navalunit =
  { name     = "USN Battleship Fleet 2"
    id       = { type = 14800 id = 31 }
    location = 761
    base     = 761
    division =
    { id            = { type = 14800 id = 32 }
      name          = "USS Saratoga"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 14800 id = 33 }
      name  = "USS Oklahoma"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 34 }
      name  = "USS Tennessee"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 35 }
      name  = "USS California"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
  }
  # Battleship Division 4
  # Colorado, West Virginia, Maryland
  navalunit =
  { name     = "USN Battleship Fleet 4"
    id       = { type = 14800 id = 36 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 37 }
      name  = "USS Colorado"
      type  = battleship
      model = 2
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 38 }
      name  = "USS West Virginia"
      type  = battleship
      model = 2
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 39 }
      name  = "USS Maryland"
      type  = battleship
      model = 2
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
  }
  # Cruiser Division 3
  # Richmond, Trenton, Concord
  navalunit =
  { name     = "USN Cruiser Fleet 3"
    id       = { type = 14800 id = 40 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 41 }
      name  = "USS Richmond"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 43 }
      name  = "USS Concord"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 44 }
      name  = "USS Raleigh"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 0
	brigade_model2 = 1
    }
    division =
    { id    = { type = 14800 id = 45 }
      name  = "USS Detroit"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 108 }
      name  = "USS Milwaukee"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 109 }
      name  = "USS Cincinnati"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 110 }
      name  = "USS Memphis"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
  }
  # USS Trenton
  navalunit = 
   { name = "USS Trenton"
	id = { type = 14800 id = 200 }
	location = 651
	base = 651
    division =
    { id    = { type = 14800 id = 42 }
      name  = "USS Trenton"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 0
	brigade_model2 = 1
    }
}
  # Cruiser Division 4
  # Pensacola, Salt Lake City, Chicago, Indianapolis
  navalunit =
  { name     = "USN Cruiser Fleet 4"
    id       = { type = 14800 id = 46 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 47 }
      name  = "USS Pensacola"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 48 }
      name  = "USS Salt Lake City"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 49 }
      name  = "USS Chicago"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 50 }
      name  = "USS Indianapolis"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_sa_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 0
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  # Cruiser Division 5
  # Northampton, Chester, Louisville, Portland
  navalunit =
  { name     = "USN Cruiser Fleet 5"
    id       = { type = 14800 id = 51 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 52 }
      name  = "USS Northampton"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 53 }
      name  = "USS Chester"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 54 }
      name  = "USS Louisville"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 55 }
      name  = "USS Portland"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_sa_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 0
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  # Cruiser Division 6
  # New Orleans, Astoria, Minneapolis, San Francisco
  navalunit =
  { name     = "USN Cruiser Fleet 6"
    id       = { type = 14800 id = 56 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 57 }
      name  = "USS New Orleans"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 58 }
      name  = "USS Astoria"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 59 }
      name  = "USS Minneapolis"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 60 }
      name  = "USS San Francisco"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  navalunit =
  { name     = "Pacific Destroyer Fleet"
    id       = { type = 14800 id = 61 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 62 }
      name  = "1st Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 63 }
      name  = "2nd Destroyer Division"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 14800 id = 64 }
      name  = "3rd Destroyer Division"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 65 }
    name     = "USN Battleship Fleet 5"
    division =
    { id    = { type = 14800 id = 66 }
      name  = "USS Arkansas"
      type  = battleship
      model = 0
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 67 }
      name  = "USS New York"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 68 }
      name  = "USS Texas"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
  }
  navalunit =
  { name     = "Pacific Submarine Fleet"
    id       = { type = 14800 id = 74 }
    location = 761
    base     = 761
    division =
    { id    = { type = 14800 id = 75 }
      name  = "1st Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 76 }
      name  = "2nd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 77 }
      name  = "3rd Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 78 }
      name  = "4th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 79 }
      name  = "5th Submarine Division"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 14800 id = 80 }
      name  = "6th Submarine Division"
      type  = submarine
      model = 0
    }
  }
  navalunit =
  { location = 1737
    base     = 1737
    id       = { type = 14800 id = 81 }
    name     = "Asiatic Fleet"
    division =
    { id    = { type = 14800 id = 82 }
      name  = "13th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 83 }
      name  = "14th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 84 }
      name  = "15th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 24 }
      name  = "31st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 25 }
      name  = "32nd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 85 }
      name  = "7th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 86 }
      name  = "8th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 1737
    base     = 1737
    id       = { type = 14800 id = 87 }
    name     = "2nd USN Submarine Fleet"
    division =
    { id    = { type = 14800 id = 88 }
      name  = "9th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 780
    base     = 780
    id       = { type = 14800 id = 89 }
    name     = "USN Seattle Fleet"
    division =
    { id       = { type = 14800 id = 90 }
      name     = "USS Marblehead"
      strength = 100
      type     = light_cruiser
      model    = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
    division =
    { id    = { type = 14800 id = 91 }
      name  = "16th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 69 }
      name  = "47th Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 780
    base     = 780
    id       = { type = 14800 id = 92 }
    name     = "USN Columbia Fleet"
    division =
    { id       = { type = 14800 id = 93 }
      name     = "USS Houston"
      strength = 100
      type     = heavy_cruiser
      model    = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 70 }
      name  = "43rd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 94 }
      name  = "10th Submarine Division"
      type  = submarine
      model = 1
    }
  }
  navalunit =
  { location = 889
    base     = 889
    id       = { type = 14800 id = 95 }
    name     = "USN Carribean Fleet"
    division =
    { id    = { type = 14800 id = 96 }
      name  = "17th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 97 }
      name  = "11th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 71 }
      name  = "41st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 72 }
      name  = "42nd Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 98 }
    name     = "USN Battleship Fleet 3"
    division =
    { id    = { type = 14800 id = 99 }
      name  = "USS New Mexico"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 100 }
      name  = "USS Mississippi"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 101 }
      name  = "USS Idaho"
      type  = battleship
      model = 1
	extra1 = naval_fire_controll_l
	extra2 = naval_sa_l
	extra3 = naval_spotter_l
	extra4 = naval_anti_air_l
	brigade_model1 = 1
	brigade_model2 = 0
	brigade_model3 = 2
	brigade_model4 = 1
    }
    division =
    { id    = { type = 14800 id = 103 }
      name  = "44th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 104 }
      name  = "45th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 105 }
      name  = "46th Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 106 }
    name     = "USN Cruiser Fleet 2"
    division =
    { id    = { type = 14800 id = 107 }
      name  = "USS Omaha"
      type  = light_cruiser
      model = 1
	extra1 = naval_fire_controll_s
	extra2 = naval_spotter_s
	brigade_model1 = 1
	brigade_model2 = 2
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 111 }
    name     = "USN Cruiser Fleet 7"
    division =
    { id    = { type = 14800 id = 112 }
      name  = "USS Augusta"
      type  = heavy_cruiser
      model = 1
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
    division =
    { id    = { type = 14800 id = 113 }
      name  = "USS Tuscaloosa"
      type  = heavy_cruiser
      model = 2
    extra1 = naval_fire_controll_l
    extra2 = naval_spotter_l
    extra3 = naval_anti_air_l
    brigade_model1 = 1
    brigade_model2 = 2
    brigade_model3 = 1
    }
  }
  navalunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 114 }
    name     = "USS Ranger Taskforce"
    division =
    { id            = { type = 14800 id = 115 }
      name          = "USS Ranger"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 14800 id = 116 }
      name  = "18th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 117 }
      name  = "19th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 118 }
      name  = "20th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 119 }
      name  = "21st Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 120 }
      name  = "22nd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 121 }
      name  = "23rd Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 122 }
      name  = "24th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 123 }
      name  = "25th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 124 }
      name  = "26th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 125 }
      name  = "27th Destroyer Division"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 14800 id = 126 }
      name  = "28th Destroyer Division"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 127 }
    name     = "Atlantic Submarine Fleet"
    division =
    { id    = { type = 14800 id = 128 }
      name  = "12th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 129 }
      name  = "13th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 130 }
      name  = "14th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 131 }
      name  = "15th Submarine Division"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 14800 id = 132 }
      name  = "16th Submarine Division"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 14800 id = 133 }
      name  = "17th Submarine Division"
      type  = submarine
      model = 7
    }
  }
  navalunit =
  { location = 633
    base     = 633
    id       = { type = 14800 id = 160 }
    name     = "Atlantic Transport Fleet"
    division =
    { id   = { type = 14800 id = 134 }
      name = "Abner Doubleday Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 135 }
      name = "Brigham Young Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 136 }
      name = "William B. Travis Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 137 }
      name = "Peter Stuyvesant Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 138 }
      name = "Henry L. Benning Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 139 }
      name = "Casimir Pulaski Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 140 }
      name = "Sam Houston Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 141 }
      name = "Francis Scott Key Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 142 }
      name = "Walter Reed Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 143 }
      name = "Dolly Madison Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 144 }
      name = "Frederick Douglass Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 145 }
      name = "Clara Barton Flotilla"
      type = transport
    }
  }
  navalunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 146 }
    name     = "Pacific Transport Fleet"
    division =
    { id   = { type = 14800 id = 147 }
      name = "Charles Goodyear Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 148 }
      name = "Anthony Wayne Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 149 }
      name = "John Hancock Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 150 }
      name = "Samuel Dexter Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 151 }
      name = "Stephen C. Crane Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 152 }
      name = "William McKinley Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 153 }
      name = "George A. Custer Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 154 }
      name = "August Belmont Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 156 }
      name = "Emily Dickinson Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 157 }
      name = "Molly Pitcher Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 158 }
      name = "Antonin Dvorak Flotilla"
      type = transport
    }
    division =
    { id   = { type = 14800 id = 159 }
      name = "J. E. B. Stuart Flotilla"
      type = transport
    }
  }
 #####################################
	### USA Air OOB ###
 #####################################
  airunit =
  { location = 761
    base     = 761
    id       = { type = 14800 id = 13 }
    name     = "1st USAAF Fighter Wing"
    division =
    { id    = { type = 14800 id = 14 }
      name  = "6th USAAF Fighter Wing"
      type  = interceptor
      model = 1
    }
  }
  airunit =
  { location = 606
    base     = 606
    id       = { type = 14800 id = 17 }
    name     = "1st USAAF Bombardment Wing"
    division =
    { id    = { type = 14800 id = 18 }
      name  = "1st USAAF Dive Bomb. Wing"
      type  = tactical_bomber
      model = 0
    }
  }
  airunit =
  { location = 889
    base     = 889
    id       = { type = 14800 id = 19 }
    name     = "5th USAAF Bombardment Wing"
    division =
    { id    = { type = 14800 id = 20 }
      name  = "5th USAAF Tactical Bomb. Wing"
      type  = tactical_bomber
      model = 0
    }
  }
  airunit =
  { location = 780
    base     = 780
    id       = { type = 14800 id = 21 }
    name     = "7th USAAF Bombardment Wing"
    division =
    { id    = { type = 14800 id = 22 }
      name  = "1st USAAF Tactical Bomb. Wing"
      type  = tactical_bomber
      model = 0
    }
  }
  airunit =
  { location = 602
    base     = 602
    id       = { type = 14800 id = 23 }
    name     = "US Army Airforce"
    division =
    { id    = { type = 14800 id = 15 }
      name  = "9th USAAF Fighter Wing"
      type  = interceptor
      model = 1
    }
    division =
    { id    = { type = 14800 id = 16 }
      name  = "2nd USAAF Tactical Bomb. Wing"
      type  = tactical_bomber
      model = 0
    }
  }
 ######################################
	### Development ###
 ###################################### 
	province_development = { 
		id = { type = 14800 id = 184 } 
		name = "" 
		progress = 0.0000 
		location = 716 
		cost = 2.0000 
		date = { 
			year = 1942 
			month = march 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 172 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 185 } 
		name = "" 
		progress = 0.0000 
		location = 677 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 186 } 
		name = "" 
		progress = 0.0000 
		location = 672 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = june 
			day = 29 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 187 } 
		name = "" 
		progress = 0.0000 
		location = 613 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 188 } 
		name = "" 
		progress = 0.0000 
		location = 602 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 189 } 
		name = "" 
		progress = 0.0000 
		location = 603 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 190 } 
		name = "" 
		progress = 0.0000 
		location = 608 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 191 } 
		name = "" 
		progress = 0.0000 
		location = 620 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 192 } 
		name = "" 
		progress = 0.0000 
		location = 604 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 193 } 
		name = "" 
		progress = 0.0000 
		location = 616 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 194 } 
		name = "" 
		progress = 0.0000 
		location = 615 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 195 } 
		name = "" 
		progress = 0.0000 
		location = 628 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 196 } 
		name = "" 
		progress = 0.0000 
		location = 606 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 197 } 
		name = "" 
		progress = 0.0000 
		location = 762 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 198 } 
		name = "" 
		progress = 0.0000 
		location = 640 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 199 } 
		name = "" 
		progress = 0.0000 
		location = 621 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 201 } 
		name = "" 
		progress = 0.0000 
		location = 693 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 202 } 
		name = "" 
		progress = 0.0000 
		location = 765 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 203 } 
		name = "" 
		progress = 0.0000 
		location = 600 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 204 } 
		name = "" 
		progress = 0.0000 
		location = 715 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 205 } 
		name = "" 
		progress = 0.0000 
		location = 601 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 206 } 
		name = "" 
		progress = 0.0000 
		location = 649 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 207 } 
		name = "" 
		progress = 0.0000 
		location = 722 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 208 } 
		name = "" 
		progress = 0.0000 
		location = 727 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 209 } 
		name = "" 
		progress = 0.0000 
		location = 609 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 210 } 
		name = "" 
		progress = 0.0000 
		location = 641 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 211 } 
		name = "" 
		progress = 0.0000 
		location = 614 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 212 } 
		name = "" 
		progress = 0.0000 
		location = 629 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 213 } 
		name = "" 
		progress = 0.0000 
		location = 630 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 214 } 
		name = "" 
		progress = 0.0000 
		location = 716 
		cost = 5.0000 
		date = { 
			year = 1952 
			month = february 
			day = 22 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 30 
		done = 0 
		days = 5472 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		speed_step = 1 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 215 } 
		name = "" 
		progress = 0.0000 
		location = 677 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 222 } 
		name = "" 
		progress = 0.0000 
		location = 649 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 223 } 
		name = "" 
		progress = 0.0000 
		location = 722 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 220 } 
		name = "" 
		progress = 0.0000 
		location = 603 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 216 } 
		name = "" 
		progress = 0.0000 
		location = 672 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 5472 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 217 } 
		name = "" 
		progress = 0.0000 
		location = 613 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 5472 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 221 } 
		name = "" 
		progress = 0.0000 
		location = 608 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 224 } 
		name = "" 
		progress = 0.0000 
		location = 606 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 218 } 
		name = "" 
		progress = 0.0000 
		location = 620 
		cost = 5.0000 
		date = { 
			year = 1945 
			month = february 
			day = 18 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 12 
		done = 0 
		days = 4925 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 232 } 
		name = "" 
		progress = 0.0000 
		location = 607 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 233 } 
		name = "" 
		progress = 0.0000 
		location = 627 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 234 } 
		name = "" 
		progress = 0.0000 
		location = 689 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 235 } 
		name = "" 
		progress = 0.0000 
		location = 619 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 236 } 
		name = "" 
		progress = 0.0000 
		location = 690 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 237 } 
		name = "" 
		progress = 0.0000 
		location = 721 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 238 } 
		name = "" 
		progress = 0.0000 
		location = 626 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 239 } 
		name = "" 
		progress = 0.0000 
		location = 625 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 240 } 
		name = "" 
		progress = 0.0000 
		location = 612 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 241 } 
		name = "" 
		progress = 0.0000 
		location = 761 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 242 } 
		name = "" 
		progress = 0.0000 
		location = 676 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 243 } 
		name = "" 
		progress = 0.0000 
		location = 669 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 244 } 
		name = "" 
		progress = 0.0000 
		location = 670 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 245 } 
		name = "" 
		progress = 0.0000 
		location = 598 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 246 } 
		name = "" 
		progress = 0.0000 
		location = 691 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 247 } 
		name = "" 
		progress = 0.0000 
		location = 692 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 248 } 
		name = "" 
		progress = 0.0000 
		location = 599 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = september 
			day = 17 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 20 
		done = 0 
		days = 1344 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 249 } 
		name = "" 
		progress = 0.0000 
		location = 618 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 250 } 
		name = "" 
		progress = 0.0000 
		location = 748 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 251 } 
		name = "" 
		progress = 0.0000 
		location = 789 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 225 } 
		name = "" 
		progress = 0.0000 
		location = 727 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 226 } 
		name = "" 
		progress = 0.0000 
		location = 609 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 227 } 
		name = "" 
		progress = 0.0000 
		location = 640 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 228 } 
		name = "" 
		progress = 0.0000 
		location = 641 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 229 } 
		name = "" 
		progress = 0.0000 
		location = 614 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 230 } 
		name = "" 
		progress = 0.0000 
		location = 629 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
	province_development = { 
		id = { type = 14800 id = 231 } 
		name = "" 
		progress = 0.0000 
		location = 630 
		cost = 5.0000 
		date = { 
			year = 1942 
			month = november 
			day = 6 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 9 
		done = 0 
		days = 3283 
		days_for_first = 274 
		gearing_bonus = 0.0000 
		type = ic 
		} 
#	province_development = { 
#		id = { type = 14800 id = 219 } 
#		name = "" 
#		progress = 0.0000 
#		location = 602 
#		cost = 5.0000 
#		date = { 
#			year = 1942 
#			month = november 
#			day = 6 
#			hour = 0 
#			} 
#		manpower = 1.0000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.0000 
#		size = 9 
#		done = 0 
#		days = 3283 
#		days_for_first = 274 
#		gearing_bonus = 0.0000 
#		type = ic 
#		} 
	province_development = { 
		id = { type = 14800 id = 252 } 
		name = "" 
		progress = 0.0000 
		location = 682 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 253 } 
		name = "" 
		progress = 0.0000 
		location = 793 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 254 } 
		name = "" 
		progress = 0.0000 
		location = 713 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 255 } 
		name = "" 
		progress = 0.0000 
		location = 763 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 256 } 
		name = "" 
		progress = 0.0000 
		location = 726 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 257 } 
		name = "" 
		progress = 0.0000 
		location = 704 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 258 } 
		name = "" 
		progress = 0.0000 
		location = 639 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 259 } 
		name = "" 
		progress = 0.0000 
		location = 694 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 260 } 
		name = "" 
		progress = 0.0000 
		location = 622 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 261 } 
		name = "" 
		progress = 0.0000 
		location = 790 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 262 } 
		name = "" 
		progress = 0.0000 
		location = 642 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 263 } 
		name = "" 
		progress = 0.0000 
		location = 684 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 264 } 
		name = "" 
		progress = 0.0000 
		location = 707 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 265 } 
		name = "" 
		progress = 0.0000 
		location = 675 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 107 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 266 } 
		name = "" 
		progress = 0.0000 
		location = 792 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 267 } 
		name = "" 
		progress = 0.0000 
		location = 645 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 268 } 
		name = "" 
		progress = 0.0000 
		location = 671 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 269 } 
		name = "" 
		progress = 0.0000 
		location = 698 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 270 } 
		name = "" 
		progress = 0.0000 
		location = 610 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 271 } 
		name = "" 
		progress = 0.0000 
		location = 791 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 86 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 272 } 
		name = "" 
		progress = 0.0000 
		location = 717 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 129 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 273 } 
		name = "" 
		progress = 0.0000 
		location = 723 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 274 } 
		name = "" 
		progress = 0.0000 
		location = 732 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 275 } 
		name = "" 
		progress = 0.0000 
		location = 706 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 276 } 
		name = "" 
		progress = 0.0000 
		location = 708 
		cost = 2.0000 
		date = { 
			year = 1940 
			month = june 
			day = 0 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 24 
		done = 0 
		days = 1598 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	province_development = { 
		id = { type = 14800 id = 277 } 
		name = "" 
		progress = 0.0000 
		location = 775 
		cost = 2.0000 
		date = { 
			year = 1941 
			month = february 
			day = 14 
			hour = 0 
			} 
		manpower = 0.1000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 28 
		done = 0 
		days = 1853 
		days_for_first = 215 
		gearing_bonus = 0.0000 
		type = infrastructure 
		} 
	convoy_development = { 
		id = { type = 14800 id = 278 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 14800 id = 279 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 14800 id = 280 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 14800 id = 281 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 14800 id = 282 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 14800 id = 283 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 3.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 1.0000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = transports 
		} 
	convoy_development = { 
		id = { type = 14800 id = 284 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = escorts 
		} 
	convoy_development = { 
		id = { type = 14800 id = 285 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = escorts 
		} 
	convoy_development = { 
		id = { type = 14800 id = 286 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = escorts 
		} 
	convoy_development = { 
		id = { type = 14800 id = 287 } 
		name = "" 
		progress = 0.0000 
		location = 0 
		cost = 2.0000 
		date = { 
			year = 1939 
			month = november 
			day = 4 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.0000 
		size = 25 
		done = 0 
		days = 1 
		days_for_first = 72 
		gearing_bonus = 0.0000 
		type = escorts 
		} 
	division_development = { 
		id = { type = 14800 id = 161 } 
		name = "USS Yorktown" 
		progress = 0.0000 
		location = 0 
		cost = 6.0137 
		date = { 
			year = 1939 
			month = july 
			day = 16 
			hour = 0 
			} 
		manpower = 2.2000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8612 # 0.4797
		size = 3 
		done = 0 
		days = 1 
		days_for_first = 642 
		gearing_bonus = 0.0000 
		type = carrier 
		extra = cag 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 2 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
#	division_development = { 
#		id = { type = 14800 id = 183 } 
#		name = "USS Enterprise" 
#		progress = 0.0000 
#		location = 0 
#		cost = 6.0137 
#		date = { 
#			year = 1937 
#			month = february 
#			day = 7 
#			hour = 0 
#			} 
#		manpower = 2.2000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.3815 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 642 
#		gearing_bonus = 0.0000 
#		type = carrier 
#		extra = cag 
#		extra1 = none 
#		extra2 = none 
#		extra3 = none 
#		extra4 = none 
#		model = 2 
#		brigade_model = 2 
#		brigade_model1 = 0 
#		brigade_model2 = 0 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
	division_development = { 
		id = { type = 14800 id = 176 } 
		name = "USS Brooklyn" 
		progress = 0.0000 
		location = 0 
		cost = 4.9707 
		date = { 
			year = 1937 
			month = july 
			day = 22 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7848 # 0.2420
		size = 4 
		done = 0 
		days = 1 
		days_for_first = 193 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 2 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
#	division_development = { 
#		id = { type = 14800 id = 175 } 
#		name = "USS Boise" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.9707 
#		date = { 
#			year = 1936 
#			month = june 
#			day = 5 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.1957 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 193 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_spotter_s 
#		extra2 = naval_anti_air_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 2 
#		brigade_model2 = 1 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
#	division_development = { 
#		id = { type = 14800 id = 177 } 
#		name = "USS Honolulu" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.9707 
#		date = { 
#			year = 1936 
#			month = june 
#			day = 23 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.1031 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 193 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_spotter_s 
#		extra2 = naval_anti_air_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 2 
#		brigade_model2 = 1 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
#	division_development = { 
#		id = { type = 14800 id = 178 } 
#		name = "USS Nashville" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.9707 
#		date = { 
#			year = 1936 
#			month = may 
#			day = 25 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.2440 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 193 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_spotter_s 
#		extra2 = naval_anti_air_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 2 
#		brigade_model2 = 1 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
#	division_development = { 
#		id = { type = 14800 id = 179 } 
#		name = "USS Philadelphia" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.9707 
#		date = { 
#			year = 1936 
#			month = june 
#			day = 6 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.1869 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 193 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_spotter_s 
#		extra2 = naval_anti_air_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 2 
#		brigade_model2 = 1 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
#	division_development = { 
#		id = { type = 14800 id = 180 } 
#		name = "USS Phoenix" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.9707 
#		date = { 
#			year = 1936 
#			month = june 
#			day = 8 
#			hour = 0 
#			} 
#		manpower = 1.4000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.1812 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 193 
#		gearing_bonus = 0.0000 
#		type = light_cruiser 
#		extra = none 
#		extra1 = naval_spotter_s 
#		extra2 = naval_anti_air_s 
#		extra3 = none 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 2 
#		brigade_model2 = 1 
#		brigade_model3 = 0 
#		brigade_model4 = 0 
#		} 
	division_development = { 
		id = { type = 14800 id = 181 } 
		name = "USS Savannah" 
		progress = 0.0000 
		location = 0 
		cost = 4.9707 
		date = { 
			year = 1937 
			month = february 
			day = 17 
			hour = 0 
			} 
		manpower = 1.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7409 # 0.3728
		size = 3 
		done = 0 
		days = 1 
		days_for_first = 193 
		gearing_bonus = 0.0000 
		type = light_cruiser 
		extra = none 
		extra1 = naval_spotter_s 
		extra2 = naval_anti_air_s 
		extra3 = none 
		extra4 = none 
		model = 3 
		brigade_model = 0 
		brigade_model1 = 2 
		brigade_model2 = 1 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 163 } 
		name = "USS Quincy" 
		progress = 0.0000 
		location = 0 
		cost = 3.7599 
		date = { 
			year = 1936 
			month = november 
			day = 29 
			hour = 0 
			} 
		manpower = 1.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.8290 
		size = 2 
		done = 0 
		days = 1 
		days_for_first = 294 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = naval_fire_controll_l 
		extra2 = naval_spotter_l 
		extra3 = naval_anti_air_l 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 1 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 172 } 
		name = "USS Vincennes" 
		progress = 0.0000 
		location = 0 
		cost = 3.7599 
		date = { 
			year = 1936 
			month = april 
			day = 17 
			hour = 0 
			} 
		manpower = 1.3000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.6352 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 294 
		gearing_bonus = 0.0000 
		type = heavy_cruiser 
		extra = none 
		extra1 = naval_fire_controll_l 
		extra2 = naval_spotter_l 
		extra3 = naval_anti_air_l 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 1 
		brigade_model2 = 2 
		brigade_model3 = 1 
		brigade_model4 = 0 
		} 
#	division_development = { 
#		id = { type = 14800 id = 171 } 
#		name = "USS Wichita" 
#		progress = 0.0000 
#		location = 0 
#		cost = 4.2199 
#		date = { 
#			year = 1936 
#			month = october 
#			day = 15 
#			hour = 0 
#			} 
#		manpower = 1.3000 
#		close_when_finished = yes 
#		waitingforclosure = no 
#		total_progress = 0.0278 
#		size = 1 
#		done = 0 
#		days = 1 
#		days_for_first = 294 
#		gearing_bonus = 0.0000 
#		type = heavy_cruiser 
#		extra = none 
#		extra1 = naval_fire_controll_l 
#		extra2 = naval_spotter_l 
#		extra3 = naval_anti_air_l 
#		extra4 = none 
#		model = 3 
#		brigade_model = 0 
#		brigade_model1 = 1 
#		brigade_model2 = 2 
#		brigade_model3 = 1 
#		brigade_model4 = 0 
#		} 
	division_development = { 
		id = { type = 14800 id = 166 } 
		name = "18th Submarine Division" 
		progress = 0.0000 
		location = 0 
		cost = 1.7600 
		date = { 
			year = 1936 
			month = may 
			day = 1 
			hour = 0 
			} 
		manpower = 0.4000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.1418 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 141 
		gearing_bonus = 0.0000 
		type = submarine 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 2 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 165 } 
		name = "29th Destroyer Division" 
		progress = 0.0000 
		location = 0 
		cost = 3.3600 
		date = { 
			year = 1936 
			month = march 
			day = 1 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.4190 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 105 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		} 
	division_development = { 
		id = { type = 14800 id = 164 } 
		name = "4th Destroyer Division" 
		progress = 0.0000 
		location = 0 
		cost = 3.3600 
		date = { 
			year = 1936 
			month = february 
			day = 0 
			hour = 0 
			} 
		manpower = 0.6000 
		close_when_finished = yes 
		waitingforclosure = no 
		total_progress = 0.7048 
		size = 1 
		done = 0 
		days = 1 
		days_for_first = 105 
		gearing_bonus = 0.0000 
		type = destroyer 
		extra = none 
		extra1 = none 
		extra2 = none 
		extra3 = none 
		extra4 = none 
		model = 1 
		brigade_model = 0 
		brigade_model1 = 0 
		brigade_model2 = 0 
		brigade_model3 = 0 
		brigade_model4 = 0 
		}
}
