
###############################
# Victory points distribution #
###############################

province = { id = 5 points = 1 } # Skapa Flow added due to its naval and air bases
province = { id = 9 points = 3 } # Glasgow # was 5 due to its low IC
province = { id = 10 points = 3 } # Edinburgh # was 5 due to its low IC
province = { id = 11 points = 4 } # Sunderland # was 10
province = { id = 12 points = 1 } # Blackpool added due to its IC and resources
province = { id = 13 points = 5 } # Sheffield added due to its high IC, resources and naval and air base
province = { id = 14 points = 5 } # Liverpool added due to its high IC, resources and naval and air bases
province = { id = 15 points = 2 } # Cardiff added due to its IC and high resources
province = { id = 16 points = 5 } # Birmingham
province = { id = 17 points = 1 } # Norwich added due to its IC and naval and air bases
province = { id = 19 points = 30 } # London # was 30
province = { id = 20 points = 1 } # Dover added due to its IC and naval and air bases
province = { id = 21 points = 1 } # Portsmouth added due to its IC and naval and air bases
province = { id = 23 points = 1 } # Plymouth added due to its IC and naval and air bases
province = { id = 28 points = 1 } # Belfast # was 5 due to its low IC
province = { id = 30 points = 2 } # Dublin
province = { id = 31 points = 3 } # Malta
province = { id = 32 points = 4 } # Brest added due to its position and naval and air bases
province = { id = 33 points = 1 } # Rennes added due to its IC
province = { id = 34 points = 1 } # Nantes added due to its IC
province = { id = 38 points = 2 } # Cherbourg added due to its air and naval bases
province = { id = 39 points = 1 } # Caen # was 5 due to its low IC
province = { id = 41 points = 1 } # Le Havre
province = { id = 43 points = 2 } # Dunkerque
province = { id = 44 points = 6 } # Lille # was 2 due to its high IC, resources and air bases
province = { id = 45 points = 1 } # Ghent added due to its IC and naval bases
province = { id = 46 points = 1 } # Rotterdam added due to its IC and naval bases
province = { id = 47 points = 5 } # Amsterdam
province = { id = 49 points = 1 } # Eindhoven added due to its IC and resources
province = { id = 50 points = 1 } # Antwerp # was 2 due to its IC and air bases
province = { id = 51 points = 3 } # Brussels
province = { id = 56 points = 30 } # Paris # was 25 due to its high IC, resources and because its a capital of a major
province = { id = 57 points = 1 } # Orleans added due to its IC
province = { id = 66 points = 1 } # Aachen added due to its resources
province = { id = 67 points = 5 } # Essen # was 25 due to its lower resources compared to other German provinces, and low IC
province = { id = 68 points = 1 } # Liege added due to its IC and resources
province = { id = 71 points = 1 } # Luxembourg
province = { id = 72 points = 9 } # Metz added due to its IC, high resources, air bases and its military significance
province = { id = 73 points = 4 } # Strasbourg # was 2 due to its resources and military significance
province = { id = 74 points = 3 } # Saarbrucken added due to its IC and resources
province = { id = 75 points = 10 } # Cologne
province = { id = 76 points = 8 } # Dortmund added due to its IC and very high resources
province = { id = 77 points = 1 } # Arnhem added due to its IC and resources
province = { id = 80 points = 3 } # Wilhelmshaven added due to its IC and naval and air bases
province = { id = 81 points = 1 } # Munster added due to its IC
province = { id = 82 points = 1 } # Kassel added due to its air bases
province = { id = 83 points = 1 } # Schweinfurt added due to its IC
province = { id = 84 points = 2 } # Erfurt was 5 due to it being of no in-game worth
province = { id = 86 points = 5 } # Hannover
province = { id = 88 points = 1 } # Hamburg # was 5 due to its low IC
province = { id = 90 points = 3 } # Kiel # was 5 due to its low IC
#province = { id = 92 points = 1 } # Århus
province = { id = 93 points = 1 } # Malmö
province = { id = 94 points = 1 } # Noginsk added because it has a significant amount of energy
province = { id = 98 points = 1 } # Göteborg # was 2 because it has the same important as Malmo and Kiruna was given VPs
province = { id = 101 points = 4 } # Stockholm
#province = { id = 105 points = 1 } # Karlstad because it is really low on IC and resources and Kiruna was given another VP
province = { id = 107 points = 5 } # Oslo
province = { id = 110 points = 2 } # Bergen added as it has naval and air bases and its military significance
province = { id = 113 points = 1 } # Falun
province = { id = 118 points = 1 } # Trondhiem added as it has military significance
province = { id = 125 points = 2 } # Narvik # was 5 as Bergen and Trondhiem were given VPs, and Narvik is not overly significant in-game
province = { id = 126 points = 2 } # Kiruna added as it is extremely resource rich in metal
province = { id = 133 points = 3 } # Murmansk # was 5 due to its small naval and air bases and geopgraphical location
province = { id = 138 points = 1 } # Vaasa
province = { id = 141 points = 1 } # Turku
province = { id = 142 points = 4 } # Helsinki # was 3 as it is by-far the most important province in Finland and is really the only one that needs defending
#province = { id = 145 points = 1 } # Viipuri as it only has IC and very little resources
province = { id = 154 points = 2 } # Archangelsk # was 5 as it has little naval and air bases, and its location undermines its significance
province = { id = 163 points = 8 } # Stalingrad # was 30 as it only has 1 IC, very little resources and manpower, but is still a place of a well-known historical battle/campaign
province = { id = 168 points = 1 } # Gorkij added as it has some IC, resources and manpower
#province = { id = 174 points = 2 } # Kalinin as it has 1 IC and very little resources
province = { id = 175 points = 30 } # Moscow # was 50 as it is not the most important province in the game
province = { id = 181 points = 1 } # Kaluga # was 2 as it only has 1 IC and some air bases
province = { id = 182 points = 1 } # Mozhaisk added as it has some energy resource
province = { id = 187 points = 10 } # Leningrad # was 30 was it only has 6 IC, little resources and manpower, but is still a place of a well-known historical battle/campaign
province = { id = 194 points = 2 } # Tallinn
province = { id = 197 points = 2 } # Riga
province = { id = 201 points = 1 } # Opochka added as it has 6 airfields
province = { id = 207 points = 2 } # Kaunas
#province = { id = 209 points = 2 } # Grodno as it has no IC, manpower or resources
province = { id = 212 points = 3 } # Minsk # was 5 as it has little resources or IC
province = { id = 217 points = 1 } # Vitebsk
province = { id = 219 points = 3 } # Smolensk # was 5 or it has little resources or IC
province = { id = 220 points = 1 } # Mogilev added as it has 1 IC and air bases
province = { id = 228 points = 1 } # Vinnitsa added as it has 3 IC and some resources and manpower
province = { id = 233 points = 1 } # Odessa # was 2 due to its low IC and small airfields
province = { id = 235 points = 2 } # Dnepropetovsk added as it has several resources and IC
province = { id = 236 points = 6 } # Krivoy Rog added as it has many resources and IC
province = { id = 238 points = 3 } # Kiev # was 5 as it has little IC or resources
province = { id = 243 points = 1 } # Kursk added as it has some resources and 1 IC
province = { id = 246 points = 2 } # Zaporozhye added as it has several resources
province = { id = 248 points = 2 } # Kharkov
province = { id = 249 points = 5 } # Stalino added as it has 4 IC, many resources, 5 manpower
province = { id = 253 points = 3 } # Sevastopol # was 2 as it has 10 naval bases and 6 air bases, being the most significant coastal province in the Black Sea
province = { id = 258 points = 2 } # Rostov
#province = { id = 293 points = 1 } # Odense as Copenhagen is much more important and Odense is low in IC and resources
province = { id = 298 points = 1 } # Magdeburg added as it has 3 IC
province = { id = 294 points = 3 } # Copenhagen # was 1 as it is by-far the most important province in Denmark
province = { id = 296 points = 2 } # Rostock added as it has 4 air bases and 10 naval bases
province = { id = 300 points = 30 } # Berlin
province = { id = 302 points = 1 } # Stettin added as it has 4 IC
province = { id = 303 points = 2 } # Danzig
province = { id = 310 points = 5 } # Leipzig
province = { id = 311 points = 6 } # Dresden # was 5 as it is high in IC
province = { id = 312 points = 2 } # Nuremberg # was 5 as other German provinces have more IC and resources
province = { id = 313 points = 4 } # Frankfurt added as it has 7 IC and 4 air bases
province = { id = 314 points = 7 } # Stuttgart # was 5 as it is high in IC
province = { id = 316 points = 1 } # Mulhouse # was 7 as it is low in everything, with some military significance
province = { id = 318 points = 1 } # Dijon added
province = { id = 320 points = 3 } # Vichy # was 5 as it is low in everything
province = { id = 323 points = 1 } # La Rochelle added
province = { id = 325 points = 5 } # Bordeaux # was 7 as it has low IC and not that many air and naval bases
#province = { id = 331 points = 2 } # Bilbao as it is very low in everything
province = { id = 333 points = 1 } # Burgos
province = { id = 334 points = 1 } # La Coruña
province = { id = 335 points = 1 } # Oporto
province = { id = 336 points = 6 } # Lissabon # was 3 as it is Portugal's most important province, being high in IC and naval and air bases
province = { id = 339 points = 1 } # Valladolid
province = { id = 341 points = 5 } # Madrid # was 3 as it is Spain's capital and is high in IC
province = { id = 342 points = 1 } # Guadalajara
#province = { id = 346 points = 1 } # Huelva as it has virtually nothing
province = { id = 347 points = 4 } # Seville # was 2 as it is high in IC and has naval and air bases
province = { id = 348 points = 6 } # Gibraltar # was 7 as other provinces in the British empire deserve VPs
#province = { id = 349 points = 1 } # Málaga as it has virtually nothing
province = { id = 351 points = 1 } # Jaen added as it has several rare materials
#province = { id = 352 points = 1 } # Murcia as it has virtually nothing
province = { id = 354 points = 2 } # València
province = { id = 356 points = 1 } # Tarragona
province = { id = 357 points = 2 } # Barcelona
province = { id = 359 points = 4 } # Toulouse # was 7 as it is low in IC, resources and manpower
province = { id = 362 points = 2 } # Montpellier added because it has some resources and 3 IC
province = { id = 364 points = 6 } # Marseille # was 7 as it has only has some IC, resources and manpower
province = { id = 365 points = 2 } # Toulon added because it has 15 metal
province = { id = 368 points = 5 } # Genoa # was 7 as other Italian territories deserve VPs
province = { id = 369 points = 1 } # La Spezia added as it has 10 naval bases
province = { id = 370 points = 8 } # Milan # was 7 as it is high in IC, resources and manpower, and has air bases
province = { id = 376 points = 2 } # Munich # was 10 as it only has 5 IC and 10 air bases
province = { id = 377 points = 2 } # Innsbruck
province = { id = 378 points = 8 } # Venice # was 7 as it is high in IC, resources and manpower, and has air and naval bases
#province = { id = 380 points = 1 } # Ljubljana as Belgrade deserves more VPs
province = { id = 382 points = 1 } # Zagreb
province = { id = 384 points = 1 } # Split
province = { id = 386 points = 1 } # Sarajevo
province = { id = 390 points = 2 } # Tirana
province = { id = 401 points = 1 } # Athens
province = { id = 409 points = 3 } # Istanbul
province = { id = 411 points = 1 } # Salonika
#province = { id = 413 points = 1 } # Skopje as it is very low in anything, and Belgrade deserves more VPs
province = { id = 415 points = 1 } # Pristina due to vp balance
province = { id = 417 points = 2 } # Sofia # was 1 as it is the capital of Bulgaria
#province = { id = 421 points = 1 } # Plovdiv as Sofia deserved another VP
province = { id = 422 points = 1 } # Varna
province = { id = 424 points = 4 } # Bucharest # was 2 as it is high in IC and the capital of Romania
#province = { id = 428 points = 1 } # Cluj-Napoca as it is very low in IC
province = { id = 431 points = 3 } # Ploesti # was 5 as Bucharest needs more VPs
province = { id = 433 points = 1 } # Iasi added as it has 3 IC
#province = { id = 437 points = 1 } # Izmir as it only has 1 IC and very little else
province = { id = 439 points = 1 } # Izmit
province = { id = 444 points = 1 } # Cyprus added as it has 4 air bases and Pang asked for it
province = { id = 445 points = 1 } # Gaziantep
province = { id = 448 points = 3 } # Ankara # was 2 as it has 6 IC and is the capital of Turkey
province = { id = 450 points = 1 } # Trebizond
province = { id = 453 points = 3 } # Belgrade # was 2 as it has 9 IC and is the capital of Yugoslavia
province = { id = 456 points = 1 } # Pecs # was 2 as Gyor deserved a VP
province = { id = 457 points = 2 } # Budapest
province = { id = 458 points = 1 } # Gyor added as it is high in metal
province = { id = 460 points = 2 } # Graz
province = { id = 462 points = 1 } # Salzburg # was 2 as Linz is given a VP
province = { id = 463 points = 6 } # Vienna
province = { id = 465 points = 1 } # Linz added as it has some IC and resources
province = { id = 469 points = 5 } # Prague # was 6 as other Czech provinces deserve VPs
province = { id = 470 points = 1 } # Pilsen
province = { id = 473 points = 4 } # Breslau added as it has 6 IC, high in energy and has airbases
province = { id = 474 points = 1 } # Ostrava added as it is high in energy and has 3IC
province = { id = 475 points = 1 } # Brno added as it has 4 IC
province = { id = 476 points = 4 } # Bratislava
province = { id = 479 points = 2 } # Cracow
province = { id = 480 points = 1 } # Kielce added as it has 4IC
province = { id = 482 points = 4 } # Oppeln added as it has 8IC and has several energy and metal
province = { id = 483 points = 1 } # Lodz # was 2 as other Polish provinces deserve VPs
province = { id = 485 points = 4 } # Warsaw
province = { id = 487 points = 1 } # Lublin added as it is high in energy
province = { id = 490 points = 1 } # Kosice # was 2 as other Czech provinces deserve VPs
province = { id = 497 points = 1 } # Debrecen
province = { id = 501 points = 2 } # Lvov
province = { id = 510 points = 3 } # Konigsberg added as it has 6 IC and 10 air and naval bases
province = { id = 512 points = 2 } # Bologna # was 5 as Turin is of more value
province = { id = 513 points = 1 } # Florence added as it has 3 IC
province = { id = 515 points = 20 } # Rome # was 15 as it is the capital of Italy
province = { id = 517 points = 1 } # Pescara added as it has 3 IC
province = { id = 518 points = 1 } # Cassino added as it is a place of a well-known historical battle/campaign
province = { id = 519 points = 1 } # Anzio added as it a place of a well-known historical battle/campaign
province = { id = 521 points = 2 } # Naples # was 6 as it only has 4 IC and some air bases
province = { id = 523 points = 2 } # Taranto # was 5 as it has no economic value, and just air and naval bases
province = { id = 525 points = 3 } # Palermo # was 5 as it just has 2 IC and air and naval bases
province = { id = 528 points = 5 } # Lyon # was 2 as it is high in IC
province = { id = 531 points = 3 } # Turin added as it has 7 IC and some resources
province = { id = 532 points = 1 } # Bern
province = { id = 533 points = 1 } # Zürich
province = { id = 534 points = 1 } # Sardinia added as it has 1 IC, some metal and air and naval bases
province = { id = 538 points = 1 } # Bermuda added as it has air and naval bases
province = { id = 539 points = 1 } # Managua
province = { id = 540 points = 1 } # San José
province = { id = 541 points = 1 } # Vancouver
#province = { id = 547 points = 1 } # Unalaska Island as it completely worthless
province = { id = 549 points = 1 } # Anchorage
province = { id = 556 points = 1 } # Vancouver Island added as it is high in metal
province = { id = 562 points = 1 } # Rowne added as it has 3 IC
#province = { id = 569 points = 1 } # Winnipeg as it does not have much IC
province = { id = 576 points = 1 } # Newfoundland added as it has 10 naval bases
province = { id = 579 points = 1 } # Halifax added as it has 10 naval bases and some IC
#province = { id = 585 points = 1 } # Montréal as Halifax is of more worth
province = { id = 588 points = 1 } # Ottawa
province = { id = 589 points = 1 } # Toronto
#province = { id = 595 points = 1 } # Concord as it has very little worth compared to many other US provinces
province = { id = 600 points = 1 } # Boston
province = { id = 602 points = 4 } # New York was 1 as it is high in IC
province = { id = 603 points = 3 } # Newark added as it is high in IC
province = { id = 604 points = 2 } # Atlantic City added as it is high in IC
province = { id = 606 points = 10 } # Washington D.C. was 1 as it is the capital of the USA
province = { id = 608 points = 3 } # Philadelphia # was 1 as it is high in IC
province = { id = 609 points = 2 } # Harrisburg added as it is high in resources and has some IC
province = { id = 613 points = 1 } # Buffalo
province = { id = 614 points = 1 } # Pittsburgh
province = { id = 615 points = 1 } # Cleveland
province = { id = 616 points = 1 } # Detroit
#province = { id = 619 points = 1 } # Indianapolis as it is very low in IC compared to other US provinces
province = { id = 620 points = 1 } # Chicago
province = { id = 621 points = 1 } # Milwaukee
province = { id = 633 points = 1 } # Norfolk
province = { id = 640 points = 1 } # Louisville
#province = { id = 642 points = 1 } # Nashville as it has little worth
#province = { id = 644 points = 1 } # Charleston as it only has 2IC
#province = { id = 645 points = 1 } # Columbia as it has little worth
#province = { id = 647 points = 1 } # Macon as it has little/ no worth
province = { id = 651 points = 1 } # Miami
province = { id = 654 points = 3 } # Havana # was 2 as it is the capital of Cuba and most of its IC is there
#province = { id = 657 points = 1 } # Guantánamo as Havana is much more important
province = { id = 662 points = 1 } # Midway Island
province = { id = 663 points = 1 } # Pearl Harbour
province = { id = 667 points = 7 } # Buenos Aires # was 6 as it is the capital of Argentina and most of its IC is there
#province = { id = 670 points = 1 } # Atlanta as it has little worth
province = { id = 672 points = 1 } # Birmingham, AL added as it is one of America's most resource rich provinces, but doesn't have more as the USA is massively under-represented
#province = { id = 675 points = 1 } # Jackson as it is near worthless
#province = { id = 676 points = 1 } # Mobile as it is near worthless
#province = { id = 680 points = 1 } # New Orleans as it is low in IC
province = { id = 682 points = 1 } # Monroe added as it is high in oil
#province = { id = 684 points = 1 } # Little Rock as it is near worthless
#province = { id = 688 points = 1 } # Springfield as it is near worthless
#province = { id = 689 points = 1 } # St. Louis as it is near worthless
#province = { id = 690 points = 1 } # Kansas City as it is near worthless
#province = { id = 692 points = 1 } # Des Moines as it is near worthless
province = { id = 693 points = 1 } # Minneapolis
#province = { id = 698 points = 1 } # Bismarck as it is near worthless
#province = { id = 707 points = 1 } # Denver as it is near worthless
province = { id = 715 points = 1 } # Dallas
province = { id = 716 points = 3 } # Houston # was 1
#province = { id = 717 points = 1 } # San Antonio as it is near worthless
province = { id = 721 points = 2 } # Lubbock added as it has over 140 oil
#province = { id = 724 points = 1 } # Albuquerque as it is near worthless
province = { id = 727 points = 1 } # Silver City added
#province = { id = 730 points = 1 } # Phoenix as it is near worthless
#province = { id = 733 points = 1 } # Salt Lake City as it is near worthless
#province = { id = 747 points = 1 } # Monterrey as it is near worthless
province = { id = 752 points = 3 } # Mexico City # was 2 as it is the capital of Mexico and high in IC
province = { id = 753 points = 1 } # Puebla
province = { id = 754 points = 1 } # Acapulco
province = { id = 755 points = 1 } # Villahermosa
province = { id = 757 points = 1 } # Guatemala
province = { id = 759 points = 1 } # San Salvador
province = { id = 760 points = 1 } # Tegucigalpa
province = { id = 761 points = 2 } # San Diego # was 1 as it has some IC and naval and air bases
province = { id = 762 points = 1 } # Los Angeles
#province = { id = 764 points = 1 } # Sacramento as it only has 4 airfields and little else
province = { id = 765 points = 3 } # San Francisco # was 1 as it has some IC and naval and air bases
#province = { id = 771 points = 1 } # Boise as it is near worthless
#province = { id = 774 points = 1 } # Great Falls as it is near worthless
#province = { id = 779 points = 1 } # Spokane as it is near worthless
province = { id = 780 points = 2 } # Seattle # was 1 as it has 10 naval and air bases
#province = { id = 783 points = 1 } # Portland as it is near worthless
#province = { id = 787 points = 1 } # Rapid City as it as it is near worthless
#province = { id = 789 points = 1 } # Omaha as it is near worthless
#province = { id = 793 points = 1 } # Tulsa as it is near worthless
#province = { id = 801 points = 1 } # Curacao as it only has 1 IC
province = { id = 803 points = 2 } # Barranquilla
province = { id = 804 points = 2 } # Maracaibo
province = { id = 811 points = 2 } # Caracas
#province = { id = 812 points = 2 } # Cúcuta as it is near worthless
province = { id = 813 points = 4 } # Bogotá # was 2 as it is the capital of Columbia
province = { id = 815 points = 2 } # Quito
province = { id = 830 points = 4 } # Lima # was 2 as it is the capital of Peru
#province = { id = 831 points = 2 } # Arequipa as it is near worthless
province = { id = 832 points = 2 } # La Paz
province = { id = 837 points = 1 } # Asunción
province = { id = 839 points = 2 } # Antofagasta
province = { id = 840 points = 2 } # Santiago
#province = { id = 843 points = 1 } # San Miguel de Tucumán as it is near worthless
#province = { id = 844 points = 2 } # Corrientes as it is near worthless
#province = { id = 845 points = 2 } # Córdoba as it is near worthless
province = { id = 848 points = 1 } # Porto Alegre added as it has a naval base, IC and some resources
province = { id = 849 points = 1 } # Montevideo
province = { id = 851 points = 1 } # Rosario added
province = { id = 852 points = 3 } # Mar del Plata # was 2 as it has 5 IC
province = { id = 853 points = 1 } # Bahia Blanca added as it has 8 naval base and 3 airfields
province = { id = 858 points = 1 } # Comordoro Rivadia added as it has 4 IC
province = { id = 864 points = 1 } # Punta Arenas
province = { id = 874 points = 1 } # Paramaribo due to metal and vp balace
#province = { id = 875 points = 2 } # Cayenne as it is near worthless
#province = { id = 879 points = 2 } # Belém as it is only has 1 IC
province = { id = 880 points = 1 } # Fortaleza added as it has 3 IC
province = { id = 881 points = 3 } # Recife # was 2 as it has 6 IC
province = { id = 882 points = 1 } # Salvador # was 2 as it only has 3 IC
#province = { id = 883 points = 3 } # Goiás as it only has 1 IC
province = { id = 884 points = 2 } # Vitória
province = { id = 885 points = 4 } # Rio de Janeiro # was 2 as it is the capital of Brazil
province = { id = 886 points = 3 } # São Paulo # was 2 as 4 IC and air and naval bases
province = { id = 888 points = 1 } # Panamá
province = { id = 889 points = 4 } # Colon # was 5 as other US provinces deserve VPs
province = { id = 892 points = 1 } # Port-au-Prince
#province = { id = 893 points = 4 } # Santiago as Santo Domingo is much more important
province = { id = 894 points = 5 } # Santo Domingo # was 1 as it is the capital of Dominican Republic
province = { id = 900 points = 5 } # Suez
province = { id = 901 points = 2 } # Port Said # was 5 as it is not as important as Suez
province = { id = 903 points = 2 } # Cairo
province = { id = 906 points = 4 } # Alexandria # was 5 as El Alamein has been given a VP
province = { id = 909 points = 1 } # El Alamein added as it is the sight of a well-known historical battle
province = { id = 919 points = 1 } # Tobruk # was 3 as it is low in naval and air bases
province = { id = 924 points = 1 } # Bengazi
province = { id = 932 points = 3 } # Tripoli
province = { id = 939 points = 3 } # Tunis # was 5 as it is low in IC and naval and air bases
province = { id = 949 points = 3 } # Algiers # was 5 as it is low in IC and naval and air bases
province = { id = 953 points = 1 } # Oran added as it has some naval and air bases
#province = { id = 957 points = 0 } # Ceuta
province = { id = 958 points = 2 } # Casablanca
province = { id = 981 points = 2 } # Dakar # was 5 as it is low in naval and air bases
province = { id = 983 points = 1 } # Bissao added as it has some naval and air bases
province = { id = 992 points = 1 } # Monrovia
province = { id = 1046 points = 2 } # Addis Ababa
#province = { id = 1092 points = 2 } # Libreville as it is near worthless
province = { id = 1095 points = 1 } # Banana
#province = { id = 1096 points = 1 } # Loanda as it is near worthless
province = { id = 1100 points = 1 } # Nova Lisboa #was 5 as it only has some resources to offer
province = { id = 1101 points = 1 } # Benguella added as it has some naval and air bases
province = { id = 1116 points = 2 } # Cape Town # was 3 as Pretoria is much more important
#province = { id = 1117 points = 2 } # Port Elisabeth as it is near worthless
province = { id = 1119 points = 1 } # Durban # was 2 as Pretoria deserves more VPs
province = { id = 1120 points = 3 } # Johannesburg
province = { id = 1121 points = 4 } # Pretoria added as it is high in IC and the capital of South Africa
#province = { id = 1122 points = 1 } # Lourenço Marques as it is near worthless
province = { id = 1123 points = 1 } # Inhambane added as it has some naval and air bases
province = { id = 1127 points = 1 } # Élisabethville
#province = { id = 1142 points = 1 } # Léopoldville as it is near worthless
province = { id = 1146 points = 1 } # Cap Verde Islands
province = { id = 1151 points = 10 } # Molotov added as it is very high in resources, particularly rare materials
#province = { id = 1163 points = 1 } # Yakutsk as it is near worthless
#province = { id = 1176 points = 1 } # Toyohara as it is near worthless
#province = { id = 1178 points = 1 } # Asahikawa as it is near worthless
province = { id = 1179 points = 3 } # Sapporo # was 2 as it is high in energy and resources
province = { id = 1180 points = 1 } # Sendai # was 5 as other Japan provinces are more important
province = { id = 1181 points = 4 } # Akita # being kept as 5 as it has IC and 10 naval and air bases
province = { id = 1182 points = 1 } # Fukushima # was 5 as other Japanese provinces are more important
province = { id = 1183 points = 1 } # Niigata # was 5 as it is low in IC and resources
province = { id = 1184 points = 30 } # Tokyo # was 10 as it is very high in IC, resources, manpower and is the capital of Japan
province = { id = 1185 points = 8 } # Nagoya # was 10 as Tokyo deserved more VPs
province = { id = 1186 points = 5 } # Kanazawa
province = { id = 1187 points = 10 } # Osaka # being kept at 10 as it is high in IC and has 10 air and naval bases
province = { id = 1188 points = 6 } # Hiroshima added as it has 4IC and air and naval bases
province = { id = 1189 points = 6 } # Shikoku # was as 5 as it has 5IC and 10 air and naval bases
province = { id = 1190 points = 8 } # Fukuoka # was 5 as it is high in energy and rares, as well as 4IC and air and naval bases
province = { id = 1191 points = 1 } # Kagoshima # was 5 as other provinces are more important and it only has 4IC
province = { id = 1193 points = 2 } # Okinawa
province = { id = 1196 points = 2 } # Busan # was 1 as it has 10 naval and air bases
province = { id = 1199 points = 1 } # Seoul
province = { id = 1201 points = 1 } # Pyongyang
province = { id = 1202 points = 1 } # Dalian added as it has air and naval bases
province = { id = 1203 points = 1 } # Tangshan added as it has 32 energy
province = { id = 1204 points = 1 } # Tianjin
province = { id = 1205 points = 4 } # Beiping # was 5 as other Shanxi provinces deserve more VPs
#province = { id = 1207 points = 1 } # Jining as it is near worthless
#province = { id = 1210 points = 1 } # Baoding as it is near worthless
#province = { id = 1214 points = 1 } # Yantai as it is near worthless
province = { id = 1215 points = 1 } # Qingdao added as it has naval bases
province = { id = 1216 points = 4 } # Jinan # was 1 as it has some IC, lots of manpower and some air bases
province = { id = 1221 points = 1 } # Hefei
province = { id = 1225 points = 3 } # Taiyuan # was 2 as it has some IC, manpower and is the capital of Shanxi
#province = { id = 1227 points = 1 } # Luoyang
province = { id = 1228 points = 2 } # Zhengzhou added as it has some resources, IC and manpower
#province = { id = 1229 points = 1 } # Nanyang as it is near worthless
province = { id = 1232 points = 1 } # Hankou
#province = { id = 1234 points = 1 } # Wuhu as it is near worthless
province = { id = 1235 points = 5 } # Nanjing # was 3 as it is the capital of the Republic of China
province = { id = 1237 points = 2 } # Shanghai
province = { id = 1238 points = 1 } # Hangzhou
province = { id = 1244 points = 1 } # Fuzhou added as it has 5 manpower and some air bases
#province = { id = 1250 points = 1 } # Ganzhou as it is near worthless
province = { id = 1251 points = 2 } # Nancheng added as it has some IC and lots of manpower
province = { id = 1253 points = 1 } # Wuchang
province = { id = 1255 points = 2 } # Changsha added as it has some IC and manpower
#province = { id = 1257 points = 1 } # Hengyang as it is near worthless
province = { id = 1258 points = 1 } # Guilin
#province = { id = 1261 points = 1 } # Huaihua as it is near worthless
#province = { id = 1268 points = 1 } # Nancheng as it is near worthless
province = { id = 1269 points = 1 } # Xi'an as has 1 IC, energy and the Xian incident
#province = { id = 1270 points = 1 } # Xianyang as it is near worthless
province = { id = 1271 points = 2 } # Yan'an # was 1 as it is the capital of Communist China
#province = { id = 1272 points = 1 } # Yuling as it is near worthless
province = { id = 1276 points = 1 } # Lanzhou added
#province = { id = 1277 points = 1 } # Tianshui as it is near worthless
#province = { id = 1280 points = 3 } # Chongqing as it is near worthless, it can get VPs through the China industry events should they occur
#province = { id = 1281 points = 1 } # Ya'anan as it is near worthless
#province = { id = 1282 points = 1 } # Kangting as it is near worthless
province = { id = 1285 points = 1 } # Dhaka added as it has IC and manpower
#province = { id = 1291 points = 1 } # Myitkyina as it is near worthless
#province = { id = 1293 points = 1 } # Xiaguan as it is near worthless
#province = { id = 1294 points = 1 } # Baoshan as it is near worthless
#province = { id = 1295 points = 1 } # Lashio as it is near worthless
province = { id = 1296 points = 1 } # Mandalay
province = { id = 1299 points = 1 } # Rangoon # was 2 as it only has a few naval and air bases
province = { id = 1305 points = 2 } # Jinghong added as it has some metal
province = { id = 1307 points = 5 } # Kunming # was 3 as it is the capital of Yunnan
#province = { id = 1309 points = 1 } # Bose as it is near worthless
#province = { id = 1310 points = 1 } # Liuzhou as it is near worthless
province = { id = 1313 points = 3 } # Guangzhou # was 2 as it has 8 IC, high in manpower and has naval bases
province = { id = 1315 points = 2 } # Hong Kong
province = { id = 1316 points = 1 } # Macao
province = { id = 1319 points = 1 } # Nanning added as it has resources and manpower
province = { id = 1321 points = 1 } # Hainan
province = { id = 1322 points = 3 } # Kaohsiung added as it has 2IC, 8 air bases and 10 naval bases
province = { id = 1323 points = 1 } # Taipei # was 10 as it only has 2IC
province = { id = 1328 points = 3 } # Hanoi # was 5 as it only has some IC, resources and naval and air bases
#province = { id = 1331 points = 1 } # Khon Kaen as it is near worthless
province = { id = 1335 points = 1 } # Nha Trang added as it has some rare materials
province = { id = 1337 points = 3 } # Saigon # was 10 as it only has some IC, resources and naval and air bases
province = { id = 1338 points = 1 } # Rach Gia added as it has some rare materials
province = { id = 1343 points = 3 } # Bangkok
province = { id = 1345 points = 1 } # Thom Buri
province = { id = 1347 points = 1 } # Kra added
province = { id = 1348 points = 1 } # Singora
province = { id = 1349 points = 2 } # Alor Star added as it has many rares and metals
province = { id = 1350 points = 2 } # Kota Bahru
province = { id = 1351 points = 1 } # Kuantan added as it has several rare materials
province = { id = 1352 points = 2 } # Kuala Lumpur # was 1 as it has many rares and metals
province = { id = 1353 points = 3 } # Singapore
province = { id = 1354 points = 1 } # Bangka Island added as it has over 20 metal
province = { id = 1355 points = 1 } # Medan # was 2 as Bangka Island deserves a VP
province = { id = 1356 points = 2 } # Dumai added as it has several rares and metals
province = { id = 1357 points = 1 } # Padang added as it has several rares
province = { id = 1358 points = 1 } # Palembang # was 2 as Dumai deserves more VPs
province = { id = 1359 points = 2 } # Oosthaven
province = { id = 1360 points = 2 } # Chengdu # was 1 as it has some IC, and 20 manpower
#province = { id = 1363 points = 1 } # Anshun as it is near worthless
province = { id = 1364 points = 1 } # Guiyang
province = { id = 1367 points = 1 } # Khabarorsk added as it has 1IC and 10 energy
#province = { id = 1371 points = 3 } # Tetyukhe as it is near worthless
province = { id = 1372 points = 10 } # Vladivostok # being kept at 10 as it is the only/main Soviet base in the area
#province = { id = 1373 points = 1 } # Spassk-Dalnij as it is near worthless
province = { id = 1379 points = 2 } # Harbin # was 4 as Xinjing is of equal value but has no VPs
province = { id = 1389 points = 2 } # Mukden
province = { id = 1390 points = 2 } # Xinjing added as it is the capital of Manchukuo
province = { id = 1397 points = 1 } # Changde # was 2 as it only has some air bases
province = { id = 1404 points = 2 } # Ulan Bator # was 1 as it is the capital of Mongolia
#province = { id = 1420 points = 1 } # Khobdo as it is near worthless
province = { id = 1422 points = 2 } # Alma-Ata # was 1 as it has 7 IC
province = { id = 1424 points = 3 } # Zhambyl added as it has over 40 rares
province = { id = 1427 points = 3 } # Tashkent # was 1 as it has 5 IC and several resources
province = { id = 1429 points = 1 } # Frunze added as it has some IC
province = { id = 1433 points = 1 } # Urumqi
province = { id = 1442 points = 2 } # Golmud # was 1 as it is the capital of Xibei
#province = { id = 1443 points = 1 } # Xining as it is near worthless
province = { id = 1453 points = 2 } # Lhasa
province = { id = 1455 points = 1 } # Punakha
province = { id = 1457 points = 2 } # Calcutta # was 5 as it only has some IC and manpower
province = { id = 1459 points = 1 } # Ranchi added as it has IC and manpower
province = { id = 1469 points = 2 } # Delhi # was 5 as it has no IC or manpower, but is the capital of India
province = { id = 1471 points = 1 } # Lucknow added as it has IC and manpower
province = { id = 1473 points = 1 } # Kathmandu
province = { id = 1485 points = 2 } # Stalinabad added as it has IC and resources
province = { id = 1486 points = 2 } # Kabul # was 1 as it is the capital of Afghanistan
province = { id = 1490 points = 1 } # Ashgabat added as it has 3IC
#province = { id = 1492 points = 1 } # Herat as it is near worthless
province = { id = 1494 points = 1 } # Karachi added as it has 8 air and naval bases
province = { id = 1497 points = 1 } # Bandar Abbas
#province = { id = 1498 points = 1 } # Babolsar as it is near worthless
province = { id = 1502 points = 3 } # Teheran # was 2 as it is the capital of Persia
province = { id = 1505 points = 3 } # Bombay # was 5 as other provinces in India deserve VPs
province = { id = 1507 points = 1 } # Hyderabad, IND added as it has IC and manpower
province = { id = 1517 points = 2 } # Columbo added as it has IC and many rares
province = { id = 1525 points = 1 } # Okhotsk
#province = { id = 1535 points = 3 } # Angutikha as it is near worthless
province = { id = 1546 points = 1 } # Kemerovo added as it is high in energy
province = { id = 1548 points = 6 } # Novosibirsk # was 1 as it is high in IC and has some resources
province = { id = 1552 points = 1 } # Omsk
province = { id = 1554 points = 1 } # Karaganda added as it is high in energy
province = { id = 1560 points = 1 } # Krasnoyarsk added as it is high in energy
province = { id = 1561 points = 1 } # Achinsk added as it is high in energy
province = { id = 1567 points = 3 } # Ufa added as it is high in resources and has some IC
province = { id = 1572 points = 6 } # Sverdlovsk added as it is high in resources and IC
province = { id = 1574 points = 2 } # Chelyabinsk added as it has some resources and IC
province = { id = 1578 points = 3 } # Aktyubinsk added as it has 30 rares
province = { id = 1599 points = 1 } # Iwo Jima
province = { id = 1601 points = 1 } # Eniwetok
province = { id = 1608 points = 1 } # Kwajalein
#province = { id = 1611 points = 1 } # Nauru as it is near worthless
province = { id = 1613 points = 2 } # Truk
#province = { id = 1618 points = 1 } # Ulithi as it is near worthless
#province = { id = 1619 points = 1 } # Yap as it is near worthless
#province = { id = 1621 points = 1 } # Palau as it is near worthless
province = { id = 1624 points = 1 } # Guam # was 2 as it only has some naval and air bases
#province = { id = 1626 points = 2 } # Tinian as it is near worthless
province = { id = 1627 points = 1 } # Saipan # was 2 as it is only a province where a historic battle occurred
province = { id = 1628 points = 1 } # Batavia # was 3 as other Dutch provinces deserve VPs
province = { id = 1630 points = 1 } # Semarang added as it has many resources
province = { id = 1632 points = 1 } # Soerabeya added as it has many resources
#province = { id = 1640 points = 2 } # Makassar as it is near worthless
#province = { id = 1650 points = 2 } # Balikpapan as it is near worthless
province = { id = 1653 points = 1 } # Menado added as it has naval bases
#province = { id = 1665 points = 2 } # Hollandia as it is near worthless
province = { id = 1670 points = 1 } # Rabaul
province = { id = 1672 points = 1 } # Lae
province = { id = 1679 points = 1 } # Port Moresby # was 2 as it only has some naval bases
#province = { id = 1682 points = 1 } # Bougainville as it is near worthless
province = { id = 1685 points = 1 } # Guadalcanal # was 2 as it is only a province a historica battle occurred
province = { id = 1692 points = 1 } # Noumea
#province = { id = 1696 points = 1 } # Townsville as it is near worthless
province = { id = 1703 points = 2 } # Darwin
province = { id = 1712 points = 1 } # Perth
province = { id = 1722 points = 2 } # Brisbane
province = { id = 1724 points = 1 } # Newcastle
province = { id = 1727 points = 3 } # Sydney
province = { id = 1728 points = 4 } # Canberra # was 2 as it is the capital of Australia
province = { id = 1730 points = 2 } # Melbourne
province = { id = 1733 points = 1 } # Adelaide
province = { id = 1734 points = 1 } # Broken Hill added as it has over 20 metal
#province = { id = 1736 points = 1 } # Mindoro as it is near worthless
province = { id = 1737 points = 4 } # Manila # was 3 as it is the capital of the Philippnes
province = { id = 1738 points = 1 } # Bataan
province = { id = 1739 points = 2 } # Clark Field # was 1 as it has several air bases
province = { id = 1745 points = 1 } # Leyte
province = { id = 1749 points = 1 } # Cagayan
#province = { id = 1750 points = 1 } # Davao as it is near worthless
#province = { id = 1752 points = 1 } # Fiji as it is near worthless
#province = { id = 1756 points = 1 } # Samoa as it is near worthless
#province = { id = 1769 points = 1 } # Tarawa as it is near worthless
province = { id = 1786 points = 1 } # Wake Island
province = { id = 1792 points = 1 } # Damascus # was 5 as it is of little worth
province = { id = 1794 points = 1 } # Beirut added
province = { id = 1797 points = 1 } # Jerusalem
province = { id = 1798 points = 1 } # Tel Aviv added as it has some air and naval bases
province = { id = 1807 points = 1 } # Riyadh
province = { id = 1819 points = 2 } # Mascate
province = { id = 1823 points = 1 } # Basrah
province = { id = 1825 points = 3 } # Abadan # was 1 as it is rich in oil
#province = { id = 1826 points = 1 } # Esfahan as it is near worthless
province = { id = 1828 points = 1 } # Kuybyshev added as it has some IC, resources, manpower and air bases
province = { id = 1844 points = 1 } # Maikop # was 2 as Grozny is more important
province = { id = 1847 points = 2 } # Grozny added as it has around 30 oil
province = { id = 1848 points = 2 } # Batum added as it has naval and air bases in an area low in them
province = { id = 1850 points = 5 } # Tblisi added as it has 8 IC
province = { id = 1856 points = 1 } # Yerevan added as it has 5 IC
#province = { id = 1859 points = 1 } # Tabriz as it is near worthless
province = { id = 1864 points = 1 } # Mosul # was 2 as Baghdad is much more important
province = { id = 1866 points = 4 } # Baghdad # was 3 as it is the capital of Iraq and has 6 IC
province = { id = 1867 points = 1 } # The Azores
province = { id = 1868 points = 1 } # Auckland
province = { id = 1871 points = 2 } # Wellington # was 1 as it is the capital of New Zealand
#province = { id = 1872 points = 1 } # Christchurch as it is near worthless
province = { id = 1907 points = 8 } # Baku added as it is resource rich and has IC and manpower
province = { id =  289 points = 1 } # Demyansk 
